/* Generated by scripts/build-plugins.mjs from plugins/image-toolkit/src/index.ts - do not edit. */

// plugins/image-toolkit/src/index.ts
import { createRequire } from "node:module";
import { basename, dirname, extname, join, resolve, sep } from "node:path";

// plugins/image-toolkit/src/codec.ts
import { Buffer as Buffer2 } from "node:buffer";
import { deflateSync, inflateSync } from "node:zlib";
var PNG_SIG = [137, 80, 78, 71, 13, 10, 26, 10];
var DEFAULT_MAX_PIXELS = 64e6;
var MIME_BY_FORMAT = {
  png: "image/png",
  jpeg: "image/jpeg",
  gif: "image/gif",
  webp: "image/webp",
  bmp: "image/bmp",
  avif: "image/avif",
  svg: "image/svg+xml"
};
var FORMAT_LABEL = {
  png: "PNG",
  jpeg: "JPEG",
  gif: "GIF",
  webp: "WEBP",
  bmp: "BMP",
  avif: "AVIF",
  svg: "SVG",
  unknown: ""
};
function asBytes(buf) {
  if (Buffer2.isBuffer(buf)) return buf;
  if (buf instanceof Uint8Array) return Buffer2.from(buf.buffer, buf.byteOffset, buf.byteLength);
  if (buf instanceof ArrayBuffer) return Buffer2.from(buf);
  throw new Error(" Buffer / Uint8Array");
}
function assertSize(width, height, maxPixels) {
  if (!Number.isInteger(width) || width <= 0) throw new Error("");
  if (!Number.isInteger(height) || height <= 0) throw new Error("");
  if (width * height > maxPixels) {
    throw new Error(`${width}×${height} = ${width * height / 1e6}M  ${maxPixels / 1e6}M `);
  }
}
function assertImage(img) {
  if (!img || typeof img !== "object") throw new Error("");
  assertSize(img.width, img.height, Number.MAX_SAFE_INTEGER);
  if (!(img.data instanceof Uint8Array) && !(img.data instanceof Uint8ClampedArray)) {
    throw new Error(" Uint8ArrayRGBA8");
  }
  if (img.data.length !== img.width * img.height * 4) {
    throw new Error(` ${img.data.length}  ${img.width}×${img.height} `);
  }
}
function looksLikeSvg(buf) {
  const head = buf.subarray(0, 2048).toString("latin1").replace(/^\uFEFF/, "").trimStart();
  if (!head.startsWith("<")) return false;
  if (/^<svg[\s/>]/i.test(head)) return true;
  return /^<(\?xml|!--|!DOCTYPE)/i.test(head) && /<svg[\s/>]/i.test(head);
}
function sniffFormat(buf) {
  let b;
  try {
    b = asBytes(buf);
  } catch {
    return "unknown";
  }
  if (b.length >= 8) {
    let png = true;
    for (let i = 0; i < 8; i++) {
      if (b[i] !== PNG_SIG[i]) {
        png = false;
        break;
      }
    }
    if (png) return "png";
  }
  if (b.length >= 3 && b[0] === 255 && b[1] === 216 && b[2] === 255) return "jpeg";
  if (b.length >= 6) {
    const magic6 = b.toString("latin1", 0, 6);
    if (magic6 === "GIF87a" || magic6 === "GIF89a") return "gif";
  }
  if (b.length >= 12 && b.toString("latin1", 0, 4) === "RIFF" && b.toString("latin1", 8, 12) === "WEBP") return "webp";
  if (b.length >= 2 && b[0] === 66 && b[1] === 77) return "bmp";
  if (b.length >= 12 && b.toString("latin1", 4, 8) === "ftyp") {
    const major = b.toString("latin1", 8, 12);
    if (major === "avif" || major === "avis") return "avif";
    const size = b.readUInt32BE(0);
    if (size >= 16 && size <= 4096 && b.length >= size) {
      const brands = b.toString("latin1", 8, Math.min(b.length, size));
      if (brands.includes("avif") || brands.includes("avis")) return "avif";
    }
  }
  if (looksLikeSvg(b)) return "svg";
  return "unknown";
}
function mimeForFormat(format) {
  return MIME_BY_FORMAT[String(format ?? "").toLowerCase()] ?? "application/octet-stream";
}
var VIEW_HINT = " 🖼 ";
function unsupportedDecode(format) {
  const label = FORMAT_LABEL[format] ?? format;
  return new Error(`${label} ${VIEW_HINT}`);
}
var jpegCodec = null;
function setJpegCodec(codec) {
  if (codec == null) {
    jpegCodec = null;
    return;
  }
  if (typeof codec.decode !== "function" || typeof codec.encode !== "function") {
    throw new Error("JPEG  decode  encode ");
  }
  jpegCodec = codec;
}
function hasJpegCodec() {
  return jpegCodec != null;
}
function requireJpegCodec() {
  if (!jpegCodec) {
    throw new Error(`JPEG  jpeg-js${VIEW_HINT}`);
  }
  return jpegCodec;
}
function jpegHeaderInfo(buf) {
  let pos = 2;
  while (pos + 4 <= buf.length) {
    if (buf[pos] !== 255) {
      pos++;
      continue;
    }
    const marker = buf[pos + 1];
    if (marker === 255) {
      pos++;
      continue;
    }
    if (marker === 216 || marker >= 208 && marker <= 217 || marker === 1) {
      pos += 2;
      continue;
    }
    if (marker === 218) break;
    const len = buf.readUInt16BE(pos + 2);
    if (len < 2) break;
    if (marker >= 192 && marker <= 207 && marker !== 196 && marker !== 200 && marker !== 204) {
      if (pos + 9 <= buf.length) {
        return { bitDepth: buf[pos + 4], height: buf.readUInt16BE(pos + 5), width: buf.readUInt16BE(pos + 7) };
      }
      return null;
    }
    pos += 2 + len;
  }
  return null;
}
function parsePng(buf) {
  if (buf.length < 8) throw new Error("PNG ");
  for (let i = 0; i < 8; i++) {
    if (buf[i] !== PNG_SIG[i]) throw new Error(" PNG ");
  }
  const out = { ihdr: null, palette: null, trns: null, idat: [] };
  let pos = 8;
  while (pos + 8 <= buf.length) {
    const len = buf.readUInt32BE(pos);
    const type = buf.toString("latin1", pos + 4, pos + 8);
    const start = pos + 8;
    if (start + len + 4 > buf.length) throw new Error(`PNG  ${type} `);
    if (type === "IHDR") out.ihdr = buf.subarray(start, start + len);
    else if (type === "PLTE") out.palette = buf.subarray(start, start + len);
    else if (type === "tRNS") out.trns = buf.subarray(start, start + len);
    else if (type === "IDAT") out.idat.push(buf.subarray(start, start + len));
    else if (type === "IEND") break;
    pos = start + len + 4;
  }
  if (!out.ihdr || out.ihdr.length < 13) throw new Error("PNG  IHDR ");
  return out;
}
function paeth(a, b, c) {
  const p = a + b - c;
  const pa = Math.abs(p - a);
  const pb = Math.abs(p - b);
  const pc = Math.abs(p - c);
  if (pa <= pb && pa <= pc) return a;
  if (pb <= pc) return b;
  return c;
}
function unfilter(raw, rowBytes, height, bpp) {
  const out = Buffer2.alloc(rowBytes * height);
  let pos = 0;
  for (let y = 0; y < height; y++) {
    const ft = raw[pos++];
    const cur = out.subarray(y * rowBytes, (y + 1) * rowBytes);
    const prev = y > 0 ? out.subarray((y - 1) * rowBytes, y * rowBytes) : null;
    raw.copy(cur, 0, pos, pos + rowBytes);
    pos += rowBytes;
    switch (ft) {
      case 0:
        break;
      case 1:
        for (let i = bpp; i < rowBytes; i++) cur[i] = cur[i] + cur[i - bpp] & 255;
        break;
      case 2:
        if (prev) for (let i = 0; i < rowBytes; i++) cur[i] = cur[i] + prev[i] & 255;
        break;
      case 3:
        for (let i = 0; i < rowBytes; i++) {
          const a = i >= bpp ? cur[i - bpp] : 0;
          const b = prev ? prev[i] : 0;
          cur[i] = cur[i] + (a + b >> 1) & 255;
        }
        break;
      case 4:
        for (let i = 0; i < rowBytes; i++) {
          const a = i >= bpp ? cur[i - bpp] : 0;
          const b = prev ? prev[i] : 0;
          const c = prev && i >= bpp ? prev[i - bpp] : 0;
          cur[i] = cur[i] + paeth(a, b, c) & 255;
        }
        break;
      default:
        throw new Error(`PNG  filter  ${ft}`);
    }
  }
  return out;
}
function sampleAt(raw, rowStart, x, ch, bitDepth, channels) {
  const bitOffset = (x * channels + ch) * bitDepth;
  const bytePos = rowStart + (bitOffset >> 3);
  if (bitDepth === 8) return raw[bytePos];
  if (bitDepth === 16) return raw[bytePos] << 8 | raw[bytePos + 1];
  const shift = 8 - bitDepth - (bitOffset & 7);
  return raw[bytePos] >> shift & (1 << bitDepth) - 1;
}
function expandToRgba(raw, width, height, bitDepth, colorType, palette, trns) {
  const out = new Uint8Array(width * height * 4);
  const channels = colorType === 2 ? 3 : colorType === 4 ? 2 : colorType === 6 ? 4 : 1;
  const bitsPerPixel = channels * bitDepth;
  const rowBytes = Math.ceil(width * bitsPerPixel / 8);
  const maxVal = (1 << bitDepth) - 1;
  const to8 = bitDepth === 8 ? (v) => v : (v) => Math.round(v * 255 / maxVal);
  for (let y = 0; y < height; y++) {
    const rowStart = y * rowBytes;
    for (let x = 0; x < width; x++) {
      const o = (y * width + x) * 4;
      if (colorType === 3) {
        const idx = sampleAt(raw, rowStart, x, 0, bitDepth, 1);
        const p = idx * 3;
        if (!palette || p + 2 >= palette.length) throw new Error(`PNG  ${idx} `);
        out[o] = palette[p];
        out[o + 1] = palette[p + 1];
        out[o + 2] = palette[p + 2];
        out[o + 3] = trns && idx < trns.length ? trns[idx] : 255;
      } else if (colorType === 0) {
        const g = to8(sampleAt(raw, rowStart, x, 0, bitDepth, channels));
        out[o] = g;
        out[o + 1] = g;
        out[o + 2] = g;
        out[o + 3] = 255;
      } else if (colorType === 4) {
        const g = to8(sampleAt(raw, rowStart, x, 0, bitDepth, channels));
        out[o] = g;
        out[o + 1] = g;
        out[o + 2] = g;
        out[o + 3] = to8(sampleAt(raw, rowStart, x, 1, bitDepth, channels));
      } else {
        out[o] = to8(sampleAt(raw, rowStart, x, 0, bitDepth, channels));
        out[o + 1] = to8(sampleAt(raw, rowStart, x, 1, bitDepth, channels));
        out[o + 2] = to8(sampleAt(raw, rowStart, x, 2, bitDepth, channels));
        out[o + 3] = colorType === 6 ? to8(sampleAt(raw, rowStart, x, 3, bitDepth, channels)) : 255;
      }
    }
  }
  return out;
}
function decodePng(buf, maxPixels) {
  const { ihdr, palette, trns, idat } = parsePng(buf);
  const width = ihdr.readUInt32BE(0);
  const height = ihdr.readUInt32BE(4);
  const bitDepth = ihdr[8];
  const colorType = ihdr[9];
  const interlace = ihdr[12];
  if (interlace === 1) throw new Error(`Adam7PNG ${VIEW_HINT}`);
  if (![1, 2, 4, 8, 16].includes(bitDepth)) throw new Error(`PNG  ${bitDepth} `);
  if (![0, 2, 3, 4, 6].includes(colorType)) throw new Error(`PNG  ${colorType} `);
  if (colorType === 3 && bitDepth === 16) throw new Error("PNG  16 ");
  assertSize(width, height, maxPixels);
  if (colorType === 3 && !palette) throw new Error("PNG  PLTE ");
  if (idat.length === 0) throw new Error("PNG  IDAT ");
  const channels = colorType === 2 ? 3 : colorType === 4 ? 2 : colorType === 6 ? 4 : 1;
  const bitsPerPixel = channels * bitDepth;
  const rowBytes = Math.ceil(width * bitsPerPixel / 8);
  const bpp = Math.max(1, Math.ceil(bitsPerPixel / 8));
  let raw;
  try {
    raw = inflateSync(Buffer2.concat(idat));
  } catch (err) {
    throw new Error(`PNG ${err.message}`);
  }
  const need = (rowBytes + 1) * height;
  if (raw.length < need) throw new Error(`PNG  ${need}  ${raw.length}`);
  const pixels = unfilter(raw, rowBytes, height, bpp);
  const data = expandToRgba(pixels, width, height, bitDepth, colorType, palette, trns);
  const hasAlpha = colorType === 4 || colorType === 6 || colorType === 3 && trns != null;
  return { width, height, data, hasAlpha, format: "png" };
}
var CRC_TABLE = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 3988292384 ^ c >>> 1 : c >>> 1;
    t[n] = c;
  }
  return t;
})();
function crc32(buf) {
  let c = 4294967295;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 255] ^ c >>> 8;
  return (c ^ 4294967295) >>> 0;
}
function pngChunk(type, data) {
  const head = Buffer2.alloc(8);
  head.writeUInt32BE(data.length, 0);
  head.write(type, 4, "latin1");
  const crcBuf = Buffer2.alloc(4);
  crcBuf.writeUInt32BE(crc32(Buffer2.concat([head.subarray(4), data])), 0);
  return Buffer2.concat([head, data, crcBuf]);
}
function encodePng(img, pngLevel) {
  const { width, height, data } = img;
  const ch = img.hasAlpha ? 4 : 3;
  const colorType = img.hasAlpha ? 6 : 2;
  const rowBytes = width * ch;
  const raw = Buffer2.alloc((rowBytes + 1) * height);
  const cur = new Uint8Array(rowBytes);
  const prev = new Uint8Array(rowBytes);
  const cands = [0, 1, 2, 3, 4].map(() => new Uint8Array(rowBytes));
  let pos = 0;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const s = (y * width + x) * 4;
      const d = x * ch;
      cur[d] = data[s];
      cur[d + 1] = data[s + 1];
      cur[d + 2] = data[s + 2];
      if (ch === 4) cur[d + 3] = data[s + 3];
    }
    let best = 0;
    let bestScore = Infinity;
    for (let f = 0; f < 5; f++) {
      const out = cands[f];
      for (let i = 0; i < rowBytes; i++) {
        const a = i >= ch ? cur[i - ch] : 0;
        const b = prev[i];
        const c = i >= ch ? prev[i - ch] : 0;
        let v;
        if (f === 0) v = cur[i];
        else if (f === 1) v = cur[i] - a;
        else if (f === 2) v = cur[i] - b;
        else if (f === 3) v = cur[i] - (a + b >> 1);
        else v = cur[i] - paeth(a, b, c);
        out[i] = v & 255;
      }
      let score = 0;
      for (let i = 0; i < rowBytes; i++) score += out[i] < 128 ? out[i] : 256 - out[i];
      if (score < bestScore) {
        bestScore = score;
        best = f;
      }
    }
    raw[pos++] = best;
    raw.set(cands[best], pos);
    pos += rowBytes;
    prev.set(cur);
  }
  const ihdr = Buffer2.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;
  ihdr[9] = colorType;
  ihdr[10] = 0;
  ihdr[11] = 0;
  ihdr[12] = 0;
  const idat = deflateSync(raw, { level: Math.min(9, Math.max(0, pngLevel)) });
  return Buffer2.concat([
    Buffer2.from(PNG_SIG),
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", idat),
    pngChunk("IEND", Buffer2.alloc(0))
  ]);
}
function decodeBmp(buf, maxPixels) {
  if (buf.length < 26) throw new Error("BMP ");
  if (buf.toString("latin1", 0, 2) !== "BM") throw new Error(" BMP ");
  const dataOffset = buf.readUInt32LE(10);
  const dibSize = buf.readUInt32LE(14);
  if (dibSize < 40) throw new Error(` BMP DIB  ${dibSize} BITMAPINFOHEADER `);
  const rawHeight = buf.readInt32LE(22);
  const width = buf.readInt32LE(18);
  const height = Math.abs(rawHeight);
  const topDown = rawHeight < 0;
  const bitCount = buf.readUInt16LE(28);
  const compression = buf.readUInt32LE(30);
  assertSize(width, height, maxPixels);
  if (compression !== 0) throw new Error(` BMP compression=${compression} BI_RGB`);
  if (bitCount !== 8 && bitCount !== 24 && bitCount !== 32) {
    throw new Error(` BMP ${bitCount}  8/24/32 `);
  }
  let palette = null;
  if (bitCount === 8) {
    const clrUsed = buf.readUInt32LE(46);
    const count = clrUsed > 0 ? clrUsed : 256;
    const pOff = 14 + dibSize;
    if (pOff + count * 4 > buf.length) throw new Error("BMP ");
    palette = new Uint8Array(count * 4);
    for (let i = 0; i < count; i++) {
      const s = pOff + i * 4;
      palette[i * 4] = buf[s + 2];
      palette[i * 4 + 1] = buf[s + 1];
      palette[i * 4 + 2] = buf[s];
      palette[i * 4 + 3] = 255;
    }
  }
  const stride = (width * bitCount + 31 >> 5) * 4;
  if (dataOffset + stride * height > buf.length) throw new Error("BMP ");
  const data = new Uint8Array(width * height * 4);
  for (let row = 0; row < height; row++) {
    const y = topDown ? row : height - 1 - row;
    const src = dataOffset + row * stride;
    for (let x = 0; x < width; x++) {
      const o = (y * width + x) * 4;
      if (bitCount === 8) {
        const idx = buf[src + x];
        const p = idx * 4;
        data[o] = palette[p];
        data[o + 1] = palette[p + 1];
        data[o + 2] = palette[p + 2];
        data[o + 3] = 255;
      } else if (bitCount === 24) {
        const s = src + x * 3;
        data[o] = buf[s + 2];
        data[o + 1] = buf[s + 1];
        data[o + 2] = buf[s];
        data[o + 3] = 255;
      } else {
        const s = src + x * 4;
        data[o] = buf[s + 2];
        data[o + 1] = buf[s + 1];
        data[o + 2] = buf[s];
        data[o + 3] = buf[s + 3];
      }
    }
  }
  return { width, height, data, hasAlpha: bitCount === 32, format: "bmp" };
}
function encodeBmp(img) {
  const { width, height, data } = img;
  const bitCount = img.hasAlpha ? 32 : 24;
  const stride = (width * bitCount + 31 >> 5) * 4;
  const fileSize = 14 + 40 + stride * height;
  const out = Buffer2.alloc(fileSize);
  out.write("BM", 0, "latin1");
  out.writeUInt32LE(fileSize, 2);
  out.writeUInt32LE(54, 10);
  out.writeUInt32LE(40, 14);
  out.writeInt32LE(width, 18);
  out.writeInt32LE(height, 22);
  out.writeUInt16LE(1, 26);
  out.writeUInt16LE(bitCount, 28);
  out.writeUInt32LE(0, 30);
  out.writeUInt32LE(stride * height, 34);
  out.writeInt32LE(2835, 38);
  out.writeInt32LE(2835, 42);
  for (let row = 0; row < height; row++) {
    const y = height - 1 - row;
    let p = 54 + row * stride;
    for (let x = 0; x < width; x++) {
      const s = (y * width + x) * 4;
      out[p++] = data[s + 2];
      out[p++] = data[s + 1];
      out[p++] = data[s];
      if (bitCount === 32) out[p++] = data[s + 3];
    }
  }
  return out;
}
async function decodeImage(buf, opts = {}) {
  const maxPixels = opts.maxPixels ?? DEFAULT_MAX_PIXELS;
  if (!Number.isInteger(maxPixels) || maxPixels <= 0) throw new Error("maxPixels ");
  const bytes = asBytes(buf);
  if (bytes.length === 0) throw new Error("");
  const format = sniffFormat(bytes);
  switch (format) {
    case "png":
      return decodePng(bytes, maxPixels);
    case "bmp":
      return decodeBmp(bytes, maxPixels);
    case "jpeg": {
      const codec = requireJpegCodec();
      const info = jpegHeaderInfo(bytes);
      if (info) assertSize(info.width, info.height, maxPixels);
      const out = codec.decode(bytes, { useTArray: true, formatAsRGBA: true });
      if (!out || !out.width || !out.height) throw new Error("JPEG ");
      assertSize(out.width, out.height, maxPixels);
      const data = out.data instanceof Uint8Array ? new Uint8Array(out.data.buffer, out.data.byteOffset, out.data.byteLength) : new Uint8Array(out.data);
      return { width: out.width, height: out.height, data, hasAlpha: false, format: "jpeg" };
    }
    case "unknown":
      throw new Error(`${VIEW_HINT}`);
    default:
      throw unsupportedDecode(format);
  }
}
async function encodeImage(img, format, opts = {}) {
  assertImage(img);
  const fmt = String(format ?? "").toLowerCase();
  if (fmt === "png") {
    const pngLevel = opts.pngLevel ?? 9;
    if (!Number.isInteger(pngLevel) || pngLevel < 0 || pngLevel > 9) throw new Error("pngLevel  0..9 ");
    return encodePng(img, pngLevel);
  }
  if (fmt === "bmp") return encodeBmp(img);
  if (fmt === "jpeg" || fmt === "jpg") {
    const codec = requireJpegCodec();
    const quality = opts.quality ?? 82;
    if (!Number.isFinite(quality) || quality < 1 || quality > 100) throw new Error("quality  1..100 ");
    const out = codec.encode({ data: img.data, width: img.width, height: img.height }, Math.round(quality));
    if (!out || !out.data) throw new Error("JPEG ");
    return Buffer2.isBuffer(out.data) ? out.data : Buffer2.from(out.data);
  }
  throw new Error(` ${format} png / jpeg / bmp`);
}

// plugins/image-toolkit/src/probe.ts
import { Buffer as Buffer3 } from "node:buffer";
function asBytes2(buf) {
  if (Buffer3.isBuffer(buf)) return buf;
  if (buf instanceof Uint8Array) return Buffer3.from(buf.buffer, buf.byteOffset, buf.byteLength);
  if (buf instanceof ArrayBuffer) return Buffer3.from(buf);
  throw new Error(" Buffer / Uint8Array");
}
function result(format, width, height, bytes, extra = {}) {
  const known = Number.isFinite(width) && Number.isFinite(height) && width > 0 && height > 0;
  const megapixels = known ? width * height / 1e6 : null;
  return {
    format,
    mime: mimeForFormat(format),
    width: known ? width : null,
    height: known ? height : null,
    bytes,
    megapixels,
    aspect: known ? Math.round(width / height * 1e4) / 1e4 : null,
    hasAlpha: false,
    ...extra
  };
}
function probePng(buf, bytes) {
  let pos = 8;
  let width = null;
  let height = null;
  let bitDepth = null;
  let colorType = null;
  let trns = false;
  let animated = false;
  while (pos + 8 <= buf.length) {
    const len = buf.readUInt32BE(pos);
    const type = buf.toString("latin1", pos + 4, pos + 8);
    const start = pos + 8;
    if (start + len + 4 > buf.length) break;
    if (type === "IHDR" && len >= 13) {
      width = buf.readUInt32BE(start);
      height = buf.readUInt32BE(start + 4);
      bitDepth = buf[start + 8];
      colorType = buf[start + 9];
    } else if (type === "tRNS") trns = true;
    else if (type === "acTL") animated = true;
    else if (type === "IEND") break;
    pos = start + len + 4;
  }
  if (colorType == null) return result("png", 0, 0, bytes);
  const hasAlpha = colorType === 4 || colorType === 6 || colorType === 3 && trns;
  return result("png", width, height, bytes, { hasAlpha, bitDepth, animated });
}
function probeJpeg(buf, bytes) {
  let pos = 2;
  let width = null;
  let height = null;
  let bitDepth = null;
  while (pos + 4 <= buf.length) {
    if (buf[pos] !== 255) {
      pos++;
      continue;
    }
    const marker = buf[pos + 1];
    if (marker === 255) {
      pos++;
      continue;
    }
    if (marker === 216 || marker >= 208 && marker <= 217 || marker === 1) {
      pos += 2;
      continue;
    }
    if (marker === 218) break;
    const len = buf.readUInt16BE(pos + 2);
    if (len < 2) break;
    if (marker >= 192 && marker <= 207 && marker !== 196 && marker !== 200 && marker !== 204) {
      if (pos + 9 <= buf.length) {
        bitDepth = buf[pos + 4];
        height = buf.readUInt16BE(pos + 5);
        width = buf.readUInt16BE(pos + 7);
      }
      break;
    }
    pos += 2 + len;
  }
  return result("jpeg", width, height, bytes, { hasAlpha: false, bitDepth });
}
function probeGif(buf, bytes) {
  const width = buf.readUInt16LE(6);
  const height = buf.readUInt16LE(8);
  const flags = buf[10];
  let pos = 13;
  if (flags & 128) pos += 3 * (1 << (flags & 7) + 1);
  let hasAlpha = false;
  let frames = 0;
  while (pos < buf.length) {
    const marker = buf[pos];
    if (marker === 59) break;
    if (marker === 33) {
      const label = buf[pos + 1];
      if (label === 249 && pos + 3 < buf.length && buf[pos + 3] & 1) hasAlpha = true;
      pos += 2;
      while (pos < buf.length) {
        const size = buf[pos];
        pos += 1 + size;
        if (size === 0) break;
      }
    } else if (marker === 44) {
      frames++;
      const localFlags = buf[pos + 9];
      pos += 10;
      if (localFlags & 128) pos += 3 * (1 << (localFlags & 7) + 1);
      pos += 1;
      while (pos < buf.length) {
        const size = buf[pos];
        pos += 1 + size;
        if (size === 0) break;
      }
    } else {
      break;
    }
  }
  return result("gif", width, height, bytes, { hasAlpha, bitDepth: 8, animated: frames > 1 });
}
function probeWebp(buf, bytes) {
  const chunk = buf.toString("latin1", 12, 16);
  let width = null;
  let height = null;
  let hasAlpha = false;
  let animated = false;
  if (chunk === "VP8X" && buf.length >= 30) {
    const flags = buf[20];
    hasAlpha = (flags & 16) !== 0;
    animated = (flags & 2) !== 0;
    width = (buf[24] | buf[25] << 8 | buf[26] << 16) + 1;
    height = (buf[27] | buf[28] << 8 | buf[29] << 16) + 1;
  } else if (chunk === "VP8 " && buf.length >= 30) {
    width = buf.readUInt16LE(26) & 16383;
    height = buf.readUInt16LE(28) & 16383;
  } else if (chunk === "VP8L" && buf.length >= 25) {
    const bits = buf.readUInt32LE(21);
    width = (bits & 16383) + 1;
    height = (bits >> 14 & 16383) + 1;
    hasAlpha = (bits >> 28 & 1) === 1;
  }
  return result("webp", width, height, bytes, { hasAlpha, animated });
}
function probeBmp(buf, bytes) {
  const dibSize = buf.readUInt32LE(14);
  if (dibSize < 40 || buf.length < 30) return result("bmp", 0, 0, bytes);
  const width = buf.readInt32LE(18);
  const rawHeight = buf.readInt32LE(22);
  const bitDepth = buf.readUInt16LE(28);
  return result("bmp", Math.abs(width), Math.abs(rawHeight), bytes, { hasAlpha: bitDepth === 32, bitDepth });
}
function probeAvif(buf, bytes) {
  const limit = Math.min(buf.length, 256 * 1024);
  let width = null;
  let height = null;
  for (let i = 4; i + 16 <= limit; i++) {
    if (buf[i] !== 105 || buf[i + 1] !== 115 || buf[i + 2] !== 112 || buf[i + 3] !== 101) continue;
    const w = buf.readUInt32BE(i + 8);
    const h = buf.readUInt32BE(i + 12);
    if (w > 0 && h > 0 && (width == null || w * h > width * height)) {
      width = w;
      height = h;
    }
  }
  const major = buf.toString("latin1", 8, 12);
  const hasAlpha = buf.subarray(0, Math.min(buf.length, 64 * 1024)).includes("alpha");
  return result("avif", width, height, bytes, { hasAlpha, animated: major === "avis" });
}
function svgSize(text) {
  const tag = /<svg\b[^>]*>/i.exec(text)?.[0] ?? "";
  const num = (name) => {
    const m = new RegExp(`\\b${name}\\s*=\\s*["']([^"']+)["']`, "i").exec(tag);
    if (!m) return null;
    const raw = m[1].trim();
    if (raw.endsWith("%")) return null;
    const v = parseFloat(raw);
    return Number.isFinite(v) && v > 0 ? v : null;
  };
  let width = num("width");
  let height = num("height");
  if (width == null || height == null) {
    const vb = /\bviewBox\s*=\s*["']\s*([-\d.eE]+)[\s,]+([-\d.eE]+)[\s,]+([-\d.eE]+)[\s,]+([-\d.eE]+)/i.exec(tag);
    if (vb) {
      if (width == null) width = parseFloat(vb[3]) || null;
      if (height == null) height = parseFloat(vb[4]) || null;
    }
  }
  return { width, height };
}
function probeSvg(buf, bytes) {
  const text = buf.subarray(0, Math.min(buf.length, 64 * 1024)).toString("utf8");
  const { width, height } = svgSize(text);
  return result("svg", width, height, bytes, { hasAlpha: true });
}
function probeImage(buf) {
  const bytes8 = asBytes2(buf);
  const bytes = bytes8.length;
  const format = sniffFormat(bytes8);
  switch (format) {
    case "png":
      return probePng(bytes8, bytes);
    case "jpeg":
      return probeJpeg(bytes8, bytes);
    case "gif":
      return probeGif(bytes8, bytes);
    case "webp":
      return probeWebp(bytes8, bytes);
    case "bmp":
      return probeBmp(bytes8, bytes);
    case "avif":
      return probeAvif(bytes8, bytes);
    case "svg":
      return probeSvg(bytes8, bytes);
    default:
      return result("unknown", null, null, bytes);
  }
}
var TAG = {
  MAKE: 271,
  MODEL: 272,
  ORIENTATION: 274,
  SOFTWARE: 305,
  DATETIME: 306,
  EXIF_IFD: 34665,
  GPS_IFD: 34853,
  EXPOSURE_TIME: 33434,
  FNUMBER: 33437,
  ISO: 34855,
  FOCAL_LENGTH: 37386,
  LENS_MODEL: 42036,
  LENS_SPEC: 42034
};
var GPS = { LAT_REF: 1, LAT: 2, LON_REF: 3, LON: 4, ALT_REF: 5, ALT: 6 };
var TYPE_SIZE = { 1: 1, 2: 1, 3: 2, 4: 4, 5: 8, 6: 1, 7: 1, 8: 2, 9: 4, 10: 8, 11: 4, 12: 8 };
function tiffReader(buf, base) {
  const order = buf.toString("latin1", base, base + 2);
  const le = order === "II";
  if (!le && order !== "MM") return null;
  const u16 = (o) => le ? buf.readUInt16LE(o) : buf.readUInt16BE(o);
  const u32 = (o) => le ? buf.readUInt32LE(o) : buf.readUInt32BE(o);
  const i32 = (o) => le ? buf.readInt32LE(o) : buf.readInt32BE(o);
  if (u16(base + 2) !== 42) return null;
  const readIfd = (ifdOffset) => {
    const map = /* @__PURE__ */ new Map();
    if (!ifdOffset || ifdOffset + 2 > buf.length) return map;
    const count = u16(ifdOffset);
    for (let i = 0; i < count; i++) {
      const e = ifdOffset + 2 + i * 12;
      if (e + 12 > buf.length) break;
      const tag = u16(e);
      const type = u16(e + 2);
      const num = u32(e + 4);
      const size = TYPE_SIZE[type];
      if (!size) continue;
      const total = size * num;
      const dataOff = total <= 4 ? e + 8 : base + u32(e + 8);
      if (dataOff + total > buf.length || dataOff < 0) continue;
      const values = [];
      for (let k = 0; k < num; k++) {
        const o = dataOff + k * size;
        if (type === 3 || type === 8) values.push(u16(o));
        else if (type === 4 || type === 11) values.push(u32(o));
        else if (type === 5) values.push(u32(o + 4) === 0 ? 0 : u32(o) / u32(o + 4));
        else if (type === 10) values.push(i32(o + 4) === 0 ? 0 : i32(o) / i32(o + 4));
        else if (type === 9) values.push(i32(o));
        else if (type === 1 || type === 7) values.push(buf[o]);
        else values.push(buf[o]);
      }
      let text = null;
      if (type === 2) {
        text = buf.toString("latin1", dataOff, dataOff + num).replace(/\0+$/, "").trim();
      }
      map.set(tag, { type, count: num, values, text });
    }
    return map;
  };
  return { readIfd, u32, u16, base, le };
}
function fmtNumber(v, digits = 1) {
  const r = Math.round(v * 10 ** digits) / 10 ** digits;
  return Number.isInteger(r) ? String(r) : r.toFixed(digits).replace(/0+$/, "").replace(/\.$/, "");
}
function fmtExposure(v) {
  if (!Number.isFinite(v) || v <= 0) return null;
  if (v < 1) return `1/${Math.round(1 / v)}`;
  return `${fmtNumber(v, 1)}s`;
}
function dms(values, ref) {
  if (!Array.isArray(values) || values.length < 3) return null;
  const [d, m, s] = values;
  let deg = (d || 0) + (m || 0) / 60 + (s || 0) / 3600;
  if (ref === "S" || ref === "W") deg = -deg;
  return Math.round(deg * 1e6) / 1e6;
}
function refChar(entry) {
  if (!entry) return "";
  if (entry.text) return entry.text.slice(0, 1);
  const v = entry.values?.[0];
  return typeof v === "number" ? String.fromCharCode(v) : "";
}
function fmtDateTime(s) {
  if (!s) return null;
  return s.replace(/^(\d{4}):(\d{2}):(\d{2})/, "$1-$2-$3").trim() || null;
}
function extractExif(buf, tiffBase) {
  const reader = tiffReader(buf, tiffBase);
  if (!reader) return null;
  const ifd0 = reader.readIfd(reader.base + reader.u32(reader.base + 4));
  const exifPointer = ifd0.get(TAG.EXIF_IFD)?.values?.[0];
  const exifIfd = exifPointer ? reader.readIfd(reader.base + exifPointer) : /* @__PURE__ */ new Map();
  const gpsPointer = ifd0.get(TAG.GPS_IFD)?.values?.[0];
  const gpsIfd = gpsPointer ? reader.readIfd(reader.base + gpsPointer) : /* @__PURE__ */ new Map();
  const out = {};
  const str = (v) => v && v.length ? v : null;
  const make = str(ifd0.get(TAG.MAKE)?.text);
  const model = str(ifd0.get(TAG.MODEL)?.text);
  const lensModel = str(exifIfd.get(TAG.LENS_MODEL)?.text);
  if (make) out.make = make;
  if (model) out.model = model;
  if (lensModel) out.lens = lensModel;
  else {
    const spec = exifIfd.get(TAG.LENS_SPEC)?.values;
    if (spec && spec.length >= 2 && spec[0]) {
      out.lens = spec[1] && spec[1] !== spec[0] ? `${fmtNumber(spec[0])}-${fmtNumber(spec[1])}mm` : `${fmtNumber(spec[0])}mm`;
    }
  }
  const fnum = exifIfd.get(TAG.FNUMBER)?.values?.[0];
  if (Number.isFinite(fnum) && fnum > 0) out.fNumber = `f/${fmtNumber(fnum, 1)}`;
  const exposure = exifIfd.get(TAG.EXPOSURE_TIME)?.values?.[0];
  const exposureStr = fmtExposure(exposure);
  if (exposureStr) out.exposureTime = exposureStr;
  const iso = exifIfd.get(TAG.ISO)?.values?.[0];
  if (Number.isFinite(iso) && iso > 0) out.iso = iso;
  const focal = exifIfd.get(TAG.FOCAL_LENGTH)?.values?.[0];
  if (Number.isFinite(focal) && focal > 0) out.focalLength = `${fmtNumber(focal, 1)}mm`;
  const dt = fmtDateTime(str(ifd0.get(TAG.DATETIME)?.text) ?? str(exifIfd.get(36867)?.text));
  if (dt) out.dateTime = dt;
  const orientation = ifd0.get(TAG.ORIENTATION)?.values?.[0];
  if (Number.isFinite(orientation) && orientation >= 1 && orientation <= 8) out.orientation = orientation;
  const software = str(ifd0.get(TAG.SOFTWARE)?.text);
  if (software) out.software = software;
  const lat = dms(gpsIfd.get(GPS.LAT)?.values, refChar(gpsIfd.get(GPS.LAT_REF)) || "N");
  const lon = dms(gpsIfd.get(GPS.LON)?.values, refChar(gpsIfd.get(GPS.LON_REF)) || "E");
  if (lat != null && lon != null) {
    const gps = { lat, lon };
    const alt = gpsIfd.get(GPS.ALT)?.values?.[0];
    if (Number.isFinite(alt)) {
      const ref = gpsIfd.get(GPS.ALT_REF)?.values?.[0];
      gps.alt = ref === 1 ? -alt : alt;
    }
    out.gps = gps;
  }
  return Object.keys(out).length > 0 ? out : null;
}
function findJpegExif(buf) {
  let pos = 2;
  while (pos + 4 <= buf.length) {
    if (buf[pos] !== 255) {
      pos++;
      continue;
    }
    const marker = buf[pos + 1];
    if (marker === 255) {
      pos++;
      continue;
    }
    if (marker === 216 || marker >= 208 && marker <= 217 || marker === 1) {
      pos += 2;
      continue;
    }
    if (marker === 218) return null;
    const len = buf.readUInt16BE(pos + 2);
    if (len < 2) return null;
    if (marker === 225) {
      const start = pos + 4;
      if (start + 6 <= buf.length && buf.toString("latin1", start, start + 6) === "Exif\0\0") return start + 6;
    }
    pos += 2 + len;
  }
  return null;
}
function parseExif(buf) {
  const bytes = asBytes2(buf);
  const format = sniffFormat(bytes);
  let tiffBase = null;
  if (format === "jpeg") tiffBase = findJpegExif(bytes);
  else if (format === "png") {
    let pos = 8;
    while (pos + 8 <= bytes.length) {
      const len = bytes.readUInt32BE(pos);
      const type = bytes.toString("latin1", pos + 4, pos + 8);
      const start = pos + 8;
      if (start + len + 4 > bytes.length) break;
      if (type === "eXIf") {
        tiffBase = start;
        break;
      }
      if (type === "IEND") break;
      pos = start + len + 4;
    }
  }
  if (tiffBase == null) return null;
  return extractExif(bytes, tiffBase);
}

// plugins/image-toolkit/src/ops.ts
function assertImage2(img, who = "") {
  if (!img || typeof img !== "object") throw new Error(`${who}`);
  const { width, height, data } = img;
  if (!Number.isInteger(width) || width <= 0) throw new Error("");
  if (!Number.isInteger(height) || height <= 0) throw new Error("");
  if (!(data instanceof Uint8Array) && !(data instanceof Uint8ClampedArray)) {
    throw new Error(`${who} Uint8ArrayRGBA8`);
  }
  if (data.length !== width * height * 4) {
    throw new Error(`${who} ${data.length}  ${width}×${height} `);
  }
  return img;
}
function newImage(width, height, hasAlpha = true) {
  return { width, height, data: new Uint8Array(width * height * 4), hasAlpha, format: "rgba" };
}
function copyImage(img) {
  return {
    width: img.width,
    height: img.height,
    data: new Uint8Array(img.data),
    hasAlpha: img.hasAlpha,
    format: img.format
  };
}
function clampView(arr) {
  return new Uint8Array(arr.buffer, arr.byteOffset, arr.byteLength);
}
function clampInt(v, lo, hi) {
  return v < lo ? lo : v > hi ? hi : v;
}
function axisWeights(srcSize, dstSize) {
  const scale = srcSize / dstSize;
  const out = new Array(dstSize);
  for (let d = 0; d < dstSize; d++) {
    const s0 = d * scale;
    const s1 = s0 + scale;
    const idx = [];
    const wts = [];
    if (scale >= 1) {
      const i0 = Math.floor(s0);
      const i1 = Math.min(srcSize - 1, Math.ceil(s1) - 1);
      for (let i = i0; i <= i1; i++) {
        const overlap = Math.min(i + 1, s1) - Math.max(i, s0);
        if (overlap > 0) {
          idx.push(i);
          wts.push(overlap);
        }
      }
    } else {
      const center = (s0 + s1) / 2 - 0.5;
      const f = Math.floor(center);
      const frac = center - f;
      const a = clampInt(f, 0, srcSize - 1);
      const b = clampInt(f + 1, 0, srcSize - 1);
      if (a === b) {
        idx.push(a);
        wts.push(1);
      } else {
        idx.push(a);
        wts.push(1 - frac);
        idx.push(b);
        wts.push(frac);
      }
    }
    const sum = wts.reduce((x, y) => x + y, 0) || 1;
    out[d] = { idx: Int32Array.from(idx), wts: Float64Array.from(wts, (v) => v / sum) };
  }
  return out;
}
function resizeImage(img, { width, height, quality } = {}) {
  void quality;
  assertImage2(img);
  let w = width == null ? null : Math.round(width);
  let h = height == null ? null : Math.round(height);
  if (w == null && h == null) throw new Error(" width  height");
  if (w != null && (!Number.isFinite(w) || w <= 0)) throw new Error("");
  if (h != null && (!Number.isFinite(h) || h <= 0)) throw new Error("");
  if (w == null) w = Math.max(1, Math.round(h * img.width / img.height));
  if (h == null) h = Math.max(1, Math.round(w * img.height / img.width));
  if (w === img.width && h === img.height) return copyImage(img);
  const { width: sw, height: sh, data } = img;
  const xw = axisWeights(sw, w);
  const yw = axisWeights(sh, h);
  const mid = new Float32Array(w * sh * 4);
  for (let y = 0; y < sh; y++) {
    const srcRow = y * sw * 4;
    const dstRow = y * w * 4;
    for (let x = 0; x < w; x++) {
      const { idx, wts } = xw[x];
      let r = 0;
      let g = 0;
      let b = 0;
      let a = 0;
      for (let k = 0; k < idx.length; k++) {
        const s = srcRow + idx[k] * 4;
        const wk = wts[k];
        r += data[s] * wk;
        g += data[s + 1] * wk;
        b += data[s + 2] * wk;
        a += data[s + 3] * wk;
      }
      const o = dstRow + x * 4;
      mid[o] = r;
      mid[o + 1] = g;
      mid[o + 2] = b;
      mid[o + 3] = a;
    }
  }
  const out = new Uint8ClampedArray(w * h * 4);
  for (let y = 0; y < h; y++) {
    const { idx, wts } = yw[y];
    const dstRow = y * w * 4;
    for (let x = 0; x < w; x++) {
      let r = 0;
      let g = 0;
      let b = 0;
      let a = 0;
      for (let k = 0; k < idx.length; k++) {
        const s = idx[k] * w * 4 + x * 4;
        const wk = wts[k];
        r += mid[s] * wk;
        g += mid[s + 1] * wk;
        b += mid[s + 2] * wk;
        a += mid[s + 3] * wk;
      }
      const o = dstRow + x * 4;
      out[o] = r;
      out[o + 1] = g;
      out[o + 2] = b;
      out[o + 3] = a;
    }
  }
  return { width: w, height: h, data: clampView(out), hasAlpha: img.hasAlpha, format: "rgba" };
}
function cropImage(img, { x = 0, y = 0, width, height } = {}) {
  assertImage2(img);
  const cx = Math.trunc(x) || 0;
  const cy = Math.trunc(y) || 0;
  const w = Math.max(1, Math.trunc(width ?? img.width));
  const h = Math.max(1, Math.trunc(height ?? img.height));
  const out = newImage(w, h, img.hasAlpha);
  const { width: sw, height: sh, data } = img;
  for (let yy = 0; yy < h; yy++) {
    const sy = cy + yy;
    if (sy < 0 || sy >= sh) continue;
    for (let xx = 0; xx < w; xx++) {
      const sx = cx + xx;
      if (sx < 0 || sx >= sw) continue;
      const s = (sy * sw + sx) * 4;
      const o = (yy * w + xx) * 4;
      out.data[o] = data[s];
      out.data[o + 1] = data[s + 1];
      out.data[o + 2] = data[s + 2];
      out.data[o + 3] = data[s + 3];
    }
  }
  return out;
}
function rotateImage(img, degrees) {
  assertImage2(img);
  if (!Number.isFinite(degrees)) throw new Error("");
  const k = (Math.round(degrees / 90) % 4 + 4) % 4;
  const { width: w, height: h, data } = img;
  if (k === 0) return copyImage(img);
  const out = newImage(k === 2 ? w : h, k === 2 ? h : w, img.hasAlpha);
  const ow = out.width;
  const oh = out.height;
  for (let y = 0; y < oh; y++) {
    for (let x = 0; x < ow; x++) {
      let sx;
      let sy;
      if (k === 1) {
        sx = y;
        sy = h - 1 - x;
      } else if (k === 2) {
        sx = w - 1 - x;
        sy = h - 1 - y;
      } else {
        sx = w - 1 - y;
        sy = x;
      }
      const s = (sy * w + sx) * 4;
      const o = (y * ow + x) * 4;
      out.data[o] = data[s];
      out.data[o + 1] = data[s + 1];
      out.data[o + 2] = data[s + 2];
      out.data[o + 3] = data[s + 3];
    }
  }
  return out;
}
function flipImage(img, axis) {
  assertImage2(img);
  if (axis !== "h" && axis !== "v") throw new Error(' "h" "v"');
  const { width: w, height: h, data } = img;
  const out = newImage(w, h, img.hasAlpha);
  for (let y = 0; y < h; y++) {
    const sy = axis === "v" ? h - 1 - y : y;
    for (let x = 0; x < w; x++) {
      const sx = axis === "h" ? w - 1 - x : x;
      const s = (sy * w + sx) * 4;
      const o = (y * w + x) * 4;
      out.data[o] = data[s];
      out.data[o + 1] = data[s + 1];
      out.data[o + 2] = data[s + 2];
      out.data[o + 3] = data[s + 3];
    }
  }
  return out;
}
function sampleBilinear(img, sx, sy, background) {
  const { width: w, height: h, data } = img;
  if (sx < -1 || sy < -1 || sx > w || sy > h) return background;
  const x0 = Math.floor(sx);
  const y0 = Math.floor(sy);
  const fx = sx - x0;
  const fy = sy - y0;
  let r = 0;
  let g = 0;
  let b = 0;
  let a = 0;
  for (let j = 0; j < 2; j++) {
    const yy = y0 + j;
    if (yy < 0 || yy >= h) continue;
    const wy = j === 0 ? 1 - fy : fy;
    if (wy === 0) continue;
    for (let i = 0; i < 2; i++) {
      const xx = x0 + i;
      if (xx < 0 || xx >= w) continue;
      const wx = i === 0 ? 1 - fx : fx;
      if (wx === 0) continue;
      const s = (yy * w + xx) * 4;
      const wxy = wx * wy;
      r += data[s] * wxy;
      g += data[s + 1] * wxy;
      b += data[s + 2] * wxy;
      a += data[s + 3] * wxy;
    }
  }
  if (x0 < 0 || x0 + 1 >= w || y0 < 0 || y0 + 1 >= h) {
    let covered = 0;
    for (let j = 0; j < 2; j++) {
      const yy = y0 + j;
      if (yy < 0 || yy >= h) continue;
      const wy = j === 0 ? 1 - fy : fy;
      for (let i = 0; i < 2; i++) {
        const xx = x0 + i;
        if (xx < 0 || xx >= w) continue;
        covered += (i === 0 ? 1 - fx : fx) * wy;
      }
    }
    if (covered < 1) {
      const rest = 1 - covered;
      r += background[0] * rest;
      g += background[1] * rest;
      b += background[2] * rest;
      a += background[3] * rest;
    }
  }
  return [r, g, b, a];
}
function rotateArbitrary(img, degrees, { background = [0, 0, 0, 0], expand = true } = {}) {
  assertImage2(img);
  if (!Number.isFinite(degrees)) throw new Error("");
  if (!Array.isArray(background) || background.length !== 4) throw new Error(" [r,g,b,a] ");
  const { width: w, height: h } = img;
  const rad = degrees * Math.PI / 180;
  const cos = Math.cos(rad);
  const sin = Math.sin(rad);
  const outW = expand ? Math.max(1, Math.ceil(Math.abs(w * cos) + Math.abs(h * sin))) : w;
  const outH = expand ? Math.max(1, Math.ceil(Math.abs(w * sin) + Math.abs(h * cos))) : h;
  const out = new Uint8ClampedArray(outW * outH * 4);
  const cx = outW / 2;
  const cy = outH / 2;
  const bg = [background[0], background[1], background[2], background[3]];
  for (let y = 0; y < outH; y++) {
    const dy = y + 0.5 - cy;
    for (let x = 0; x < outW; x++) {
      const dx = x + 0.5 - cx;
      const sx = dx * cos + dy * sin + w / 2 - 0.5;
      const sy = -dx * sin + dy * cos + h / 2 - 0.5;
      const [r, g, b, a] = sampleBilinear(img, sx, sy, bg);
      const o = (y * outW + x) * 4;
      out[o] = r;
      out[o + 1] = g;
      out[o + 2] = b;
      out[o + 3] = a;
    }
  }
  return { width: outW, height: outH, data: clampView(out), hasAlpha: true, format: "rgba" };
}
function boxBlurOnce(src, w, h, radius) {
  const len = w * h * 4;
  const tmp = new Uint8ClampedArray(len);
  const out = new Uint8ClampedArray(len);
  const win = radius * 2 + 1;
  const maxX = w - 1;
  const maxY = h - 1;
  for (let y = 0; y < h; y++) {
    const base = y * w * 4;
    for (let c = 0; c < 3; c++) {
      let sum = 0;
      for (let k = -radius; k <= radius; k++) sum += src[base + clampInt(k, 0, maxX) * 4 + c];
      for (let x = 0; x < w; x++) {
        tmp[base + x * 4 + c] = sum / win;
        sum += src[base + clampInt(x + radius + 1, 0, maxX) * 4 + c] - src[base + clampInt(x - radius, 0, maxX) * 4 + c];
      }
    }
    for (let x = 0; x < w; x++) tmp[base + x * 4 + 3] = src[base + x * 4 + 3];
  }
  for (let x = 0; x < w; x++) {
    for (let c = 0; c < 3; c++) {
      let sum = 0;
      for (let k = -radius; k <= radius; k++) sum += tmp[clampInt(k, 0, maxY) * w * 4 + x * 4 + c];
      for (let y = 0; y < h; y++) {
        out[y * w * 4 + x * 4 + c] = sum / win;
        sum += tmp[clampInt(y + radius + 1, 0, maxY) * w * 4 + x * 4 + c] - tmp[clampInt(y - radius, 0, maxY) * w * 4 + x * 4 + c];
      }
    }
    for (let y = 0; y < h; y++) out[y * w * 4 + x * 4 + 3] = tmp[y * w * 4 + x * 4 + 3];
  }
  return out;
}
function boxBlur(src, w, h, radius, passes) {
  let cur = src;
  for (let i = 0; i < passes; i++) cur = boxBlurOnce(cur, w, h, radius);
  return cur;
}
var LUMA = [0.2126, 0.7152, 0.0722];
var SEPIA = [
  [0.393, 0.769, 0.189],
  [0.349, 0.686, 0.168],
  [0.272, 0.534, 0.131]
];
function mul3(a, b) {
  const out = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
  ];
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 3; j++) out[i][j] = a[i][0] * b[0][j] + a[i][1] * b[1][j] + a[i][2] * b[2][j];
  }
  return out;
}
function hueMatrix(deg) {
  const rad = deg * Math.PI / 180;
  const c = Math.cos(rad);
  const s = Math.sin(rad);
  return [
    [0.213 + c * 0.787 - s * 0.213, 0.715 - c * 0.715 - s * 0.715, 0.072 - c * 0.072 + s * 0.928],
    [0.213 - c * 0.213 + s * 0.143, 0.715 + c * 0.285 + s * 0.14, 0.072 - c * 0.072 - s * 0.283],
    [0.213 - c * 0.213 - s * 0.787, 0.715 - c * 0.715 + s * 0.715, 0.072 + c * 0.928 + s * 0.072]
  ];
}
function satMatrix(percent) {
  const s = percent / 100;
  const k = 1 - s;
  const [wr, wg, wb] = LUMA;
  return [
    [s + k * wr, k * wg, k * wb],
    [k * wr, s + k * wg, k * wb],
    [k * wr, k * wg, s + k * wb]
  ];
}
function grayMatrix(percent) {
  const g = percent / 100;
  const [wr, wg, wb] = LUMA;
  return [
    [1 - g + g * wr, g * wg, g * wb],
    [g * wr, 1 - g + g * wg, g * wb],
    [g * wr, g * wg, 1 - g + g * wb]
  ];
}
function sepiaMatrix(percent) {
  const p = percent / 100;
  return SEPIA.map((row, i) => row.map((v, j) => (i === j ? 1 - p : 0) + v * p));
}
function adjustImage(img, opts = {}) {
  assertImage2(img);
  const brightness = opts.brightness ?? 100;
  const contrast = opts.contrast ?? 100;
  const saturation = opts.saturation ?? 100;
  const hue = opts.hue ?? 0;
  const gamma = opts.gamma ?? 100;
  const grayscale = opts.grayscale ?? 0;
  const sepia = opts.sepia ?? 0;
  const invert = opts.invert ?? 0;
  const blur = opts.blur ?? 0;
  const sharpen = opts.sharpen ?? 0;
  const vignette = opts.vignette ?? 0;
  for (const [name, v, lo, hi] of [
    ["", brightness, 0, 1e3],
    ["", contrast, 0, 1e3],
    ["", saturation, 0, 1e3],
    ["gamma", gamma, 1, 1e3],
    ["", grayscale, 0, 100],
    ["", sepia, 0, 100],
    ["", invert, 0, 100],
    ["", blur, 0, 50],
    ["", sharpen, 0, 100],
    ["", vignette, 0, 100]
  ]) {
    if (!Number.isFinite(v) || v < lo || v > hi) throw new Error(`${name} ${lo}..${hi} `);
  }
  if (!Number.isFinite(hue)) throw new Error("");
  const { width: w, height: h, data } = img;
  const toneLut = new Uint8ClampedArray(256);
  const bf = brightness / 100;
  const cf = contrast / 100;
  for (let v = 0; v < 256; v++) toneLut[v] = (v * bf - 128) * cf + 128;
  const m1 = mul3(hueMatrix(hue), satMatrix(saturation));
  let m2 = grayMatrix(grayscale);
  m2 = mul3(sepiaMatrix(sepia), m2);
  const invScale = 1 - 2 * invert / 100;
  const invOffset = 255 * invert / 100;
  for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) m2[i][j] *= invScale;
  const gammaLut = new Uint8ClampedArray(256);
  const exp = 100 / gamma;
  for (let v = 0; v < 256; v++) gammaLut[v] = 255 * Math.pow(v / 255, exp);
  let vig = null;
  if (vignette > 0) {
    vig = new Float32Array(w * h);
    const cx = (w - 1) / 2;
    const cy = (h - 1) / 2;
    const maxD = Math.hypot(cx, cy) || 1;
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const d = Math.hypot(x - cx, y - cy) / maxD;
        vig[y * w + x] = 1 - vignette / 100 * d * d;
      }
    }
  }
  const out = new Uint8ClampedArray(data.length);
  const rowM = [m1[0][0], m1[0][1], m1[0][2], m1[1][0], m1[1][1], m1[1][2], m1[2][0], m1[2][1], m1[2][2]];
  const rowS = [m2[0][0], m2[0][1], m2[0][2], m2[1][0], m2[1][1], m2[1][2], m2[2][0], m2[2][1], m2[2][2]];
  for (let i = 0, p = 0; i < data.length; i += 4, p++) {
    const r0 = toneLut[data[i]];
    const g0 = toneLut[data[i + 1]];
    const b0 = toneLut[data[i + 2]];
    const r1 = rowM[0] * r0 + rowM[1] * g0 + rowM[2] * b0;
    const g1 = rowM[3] * r0 + rowM[4] * g0 + rowM[5] * b0;
    const b1 = rowM[6] * r0 + rowM[7] * g0 + rowM[8] * b0;
    const r2 = rowS[0] * r1 + rowS[1] * g1 + rowS[2] * b1 + invOffset;
    const g2 = rowS[3] * r1 + rowS[4] * g1 + rowS[5] * b1 + invOffset;
    const b2 = rowS[6] * r1 + rowS[7] * g1 + rowS[8] * b1 + invOffset;
    const rf = r2 < 0 ? 0 : r2 > 255 ? 255 : r2;
    const gf = g2 < 0 ? 0 : g2 > 255 ? 255 : g2;
    const bf2 = b2 < 0 ? 0 : b2 > 255 ? 255 : b2;
    let vr = gammaLut[rf + 0.5 | 0];
    let vg = gammaLut[gf + 0.5 | 0];
    let vb = gammaLut[bf2 + 0.5 | 0];
    if (vig) {
      const f = vig[p];
      vr *= f;
      vg *= f;
      vb *= f;
    }
    out[i] = vr;
    out[i + 1] = vg;
    out[i + 2] = vb;
    out[i + 3] = data[i + 3];
  }
  let result2 = out;
  if (blur > 0) result2 = boxBlur(result2, w, h, Math.max(1, Math.round(blur)), 3);
  if (sharpen > 0) {
    const amount = sharpen / 100;
    const blurred = boxBlur(result2, w, h, 1, 1);
    const sharp = new Uint8ClampedArray(result2.length);
    for (let i = 0; i < result2.length; i += 4) {
      for (let c = 0; c < 3; c++) {
        const o = result2[i + c];
        sharp[i + c] = o + amount * (o - blurred[i + c]);
      }
      sharp[i + 3] = result2[i + 3];
    }
    result2 = sharp;
  }
  return { width: w, height: h, data: clampView(result2), hasAlpha: img.hasAlpha, format: "rgba" };
}
function compositeOverlay(base, overlay, { x = 0, y = 0, opacity = 1, scale = 1, tile = false, gap = 8 } = {}) {
  assertImage2(base, "");
  assertImage2(overlay, "");
  if (!Number.isFinite(opacity) || opacity < 0 || opacity > 1) throw new Error(" 0..1 ");
  if (!Number.isFinite(scale) || scale <= 0) throw new Error("");
  if (!Number.isFinite(gap) || gap < 0) throw new Error("");
  const ov = scale === 1 ? overlay : resizeImage(overlay, { width: Math.max(1, Math.round(overlay.width * scale)) });
  const { width: bw, height: bh, data } = base;
  const out = new Uint8ClampedArray(data);
  const ow = ov.width;
  const oh = ov.height;
  const ox = Math.trunc(x) || 0;
  const oy = Math.trunc(y) || 0;
  const blendOne = (px, py) => {
    for (let sy = 0; sy < oh; sy++) {
      const ty = py + sy;
      if (ty < 0 || ty >= bh) continue;
      for (let sx = 0; sx < ow; sx++) {
        const tx = px + sx;
        if (tx < 0 || tx >= bw) continue;
        const s = (sy * ow + sx) * 4;
        const o = (ty * bw + tx) * 4;
        const sa = ov.data[s + 3] / 255 * opacity;
        if (sa <= 0) continue;
        const ia = 1 - sa;
        out[o] = ov.data[s] * sa + out[o] * ia;
        out[o + 1] = ov.data[s + 1] * sa + out[o + 1] * ia;
        out[o + 2] = ov.data[s + 2] * sa + out[o + 2] * ia;
        out[o + 3] = (sa + out[o + 3] / 255 * ia) * 255;
      }
    }
  };
  if (tile) {
    const stepX = ow + Math.round(gap);
    const stepY = oh + Math.round(gap);
    for (let py = 0; py < bh; py += stepY) {
      for (let px = 0; px < bw; px += stepX) blendOne(px, py);
    }
  } else {
    blendOne(ox, oy);
  }
  return { width: bw, height: bh, data: clampView(out), hasAlpha: true, format: "rgba" };
}
function histogram(img, bins = 256) {
  assertImage2(img);
  if (!Number.isInteger(bins) || bins <= 0 || bins > 65536) throw new Error(" 1..65536 ");
  const { data } = img;
  const r = new Float64Array(bins);
  const g = new Float64Array(bins);
  const b = new Float64Array(bins);
  const luma = new Float64Array(bins);
  for (let i = 0; i < data.length; i += 4) {
    r[Math.min(bins - 1, Math.floor(data[i] * bins / 256))]++;
    g[Math.min(bins - 1, Math.floor(data[i + 1] * bins / 256))]++;
    b[Math.min(bins - 1, Math.floor(data[i + 2] * bins / 256))]++;
    const y = 0.2126 * data[i] + 0.7152 * data[i + 1] + 0.0722 * data[i + 2];
    luma[Math.min(bins - 1, Math.floor(y * bins / 256))]++;
  }
  const norm = (arr) => {
    let max = 0;
    for (let i = 0; i < arr.length; i++) if (arr[i] > max) max = arr[i];
    const out = new Array(bins);
    for (let i = 0; i < arr.length; i++) out[i] = max > 0 ? arr[i] / max : 0;
    return out;
  };
  return { r: norm(r), g: norm(g), b: norm(b), luma: norm(luma) };
}
function dominantColors(img, count = 6) {
  assertImage2(img);
  if (!Number.isInteger(count) || count <= 0) throw new Error("");
  const { data } = img;
  const buckets = /* @__PURE__ */ new Set();
  let total = 0;
  const rs = new Float64Array(4096);
  const gs = new Float64Array(4096);
  const bs = new Float64Array(4096);
  const ns = new Float64Array(4096);
  for (let i = 0; i < data.length; i += 4) {
    if (data[i + 3] < 8) continue;
    const key = data[i] >> 4 << 8 | data[i + 1] >> 4 << 4 | data[i + 2] >> 4;
    if (ns[key] === 0) buckets.add(key);
    rs[key] += data[i];
    gs[key] += data[i + 1];
    bs[key] += data[i + 2];
    ns[key]++;
    total++;
  }
  if (total === 0) return [];
  const keys = [...buckets].sort((a, b) => ns[b] - ns[a]).slice(0, count);
  return keys.map((k) => ({
    rgb: [Math.round(rs[k] / ns[k]), Math.round(gs[k] / ns[k]), Math.round(bs[k] / ns[k])],
    share: ns[k] / total
  }));
}

// plugins/image-toolkit/src/index.ts
var IMAGE_EXT = /* @__PURE__ */ new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".bmp", ".avif", ".svg", ".ico"]);
var SERVER_DECODE = /* @__PURE__ */ new Set(["png", "jpeg", "bmp"]);
var SERVER_ENCODE = /* @__PURE__ */ new Set(["png", "jpeg", "bmp"]);
var EXT_OF = { jpeg: "jpg", png: "png", bmp: "bmp", webp: "webp", avif: "avif", gif: "gif" };
var MAX_PIXELS = 64e6;
var isImageName = (name) => IMAGE_EXT.has(extname(name).toLowerCase());
function normalizeRel(p) {
  return String(p ?? "").replace(/\\/g, "/").replace(/^\.\//, "").trim();
}
function fmtBytes(n) {
  if (!Number.isFinite(n)) return "?";
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(2)} MB`;
}
function pretty(cwd, rel) {
  const abs = resolve(cwd, rel);
  const relToCwd = abs.startsWith(resolve(cwd) + sep) ? abs.slice(resolve(cwd).length + 1) : abs;
  return relToCwd.split(sep).join("/");
}
function parseColor(c) {
  if (Array.isArray(c)) {
    const [r, g, b, a2 = 255] = c.map(Number);
    return [r | 0, g | 0, b | 0, a2 | 0];
  }
  const m = /^#?([0-9a-f]{6})([0-9a-f]{2})?$/i.exec(String(c ?? "").trim());
  if (!m) return null;
  const hex = m[1];
  const a = m[2] ?? "ff";
  return [
    Number.parseInt(hex.slice(0, 2), 16),
    Number.parseInt(hex.slice(2, 4), 16),
    Number.parseInt(hex.slice(4, 6), 16),
    Number.parseInt(a, 16)
  ];
}
function pathList(params) {
  const raw = [];
  if (typeof params.path === "string" && params.path.trim()) raw.push(params.path);
  if (Array.isArray(params.paths)) {
    for (const p of params.paths) if (typeof p === "string" && p.trim()) raw.push(p);
  }
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const p of raw) {
    const n = normalizeRel(p);
    if (!n || seen.has(n)) continue;
    seen.add(n);
    out.push(n);
  }
  return out;
}
var index_default = {
  activate(host) {
    let cfg = host.getSettings?.() ?? {};
    let offTools = [];
    let toolsOn = false;
    let jpegTried = false;
    async function ensureJpeg() {
      if (hasJpegCodec()) return true;
      if (cfg.allowServerDeps === false) return false;
      if (jpegTried) return false;
      jpegTried = true;
      try {
        const ok = await host.ensureDeps(["jpeg-js"], {
          onProgress: (m) => host.notify("info", m, m)
        });
        if (!ok) return false;
        const require2 = createRequire(join(host.dir, "index.mjs"));
        setJpegCodec(require2("jpeg-js"));
        host.log("jpeg-js  JPEG");
        return true;
      } catch (err) {
        host.log("jpeg-js ", err);
        return false;
      }
    }
    async function loadImage(rel) {
      const buf = await host.fs.read(rel);
      const format = sniffFormat(buf);
      if (!SERVER_DECODE.has(format)) {
        throw new Error(` PNG / JPEG / BMP ${format}WebP / GIF / AVIF  🖼 Canvas `);
      }
      if (format === "jpeg" && !await ensureJpeg()) {
        throw new Error(" JPEG  JS  jpeg-js JS  PNG");
      }
      const img = await decodeImage(buf, { maxPixels: MAX_PIXELS });
      return { buf, format, img };
    }
    async function listDir(relDir) {
      const entries = await host.fs.list(relDir);
      return entries.filter((e) => !e.name.startsWith(".") && e.name !== "node_modules" && e.name !== "__pycache__").map((e) => ({
        name: e.name,
        type: e.type,
        path: relDir ? `${relDir}/${e.name}` : e.name,
        isImage: e.type === "file" && isImageName(e.name)
      })).sort((a, b) => {
        if (a.type !== b.type) return a.type === "dir" ? -1 : 1;
        if (a.isImage !== b.isImage) return a.isImage ? -1 : 1;
        return a.name.localeCompare(b.name);
      });
    }
    async function scanImages(relDir, depth, acc, depthLimit = 3) {
      const entries = await listDir(relDir).catch(() => []);
      for (const e of entries) {
        if (acc.length >= 200) return acc;
        if (e.type === "dir") {
          if (depth < depthLimit) await scanImages(e.path, depth + 1, acc, depthLimit);
        } else if (e.isImage) {
          acc.push(e.path);
        }
      }
      return acc;
    }
    async function resolveOutPath(rel, ext, o) {
      const suffix = typeof o.suffix === "string" ? o.suffix : String(cfg.suffix ?? "-min");
      const explicit = Boolean(o.out);
      let relOut;
      if (explicit) {
        relOut = normalizeRel(o.out);
      } else {
        const dir2 = o.outDir ? normalizeRel(o.outDir) : normalizeRel(dirname(rel));
        const base = basename(rel, extname(rel));
        const name2 = `${base}${suffix}.${ext}`;
        relOut = dir2 && dir2 !== "." ? `${dir2}/${name2}` : name2;
      }
      if (o.overwrite || explicit) return relOut;
      const dir = normalizeRel(dirname(relOut));
      const names = new Set((await host.fs.list(dir || "").catch(() => [])).map((e2) => e2.name));
      const name = basename(relOut);
      if (!names.has(name)) return relOut;
      const stem = basename(name, extname(name));
      const e = extname(name);
      for (let i = 1; i < 1e3; i++) {
        const candidate = `${stem}-${i}${e}`;
        if (!names.has(candidate)) return dir && dir !== "." ? `${dir}/${candidate}` : candidate;
      }
      return relOut;
    }
    async function writeImage(img, format, quality, rel, o) {
      if (!SERVER_ENCODE.has(format)) {
        throw new Error(` PNG / JPEG / BMP ${format}WebP/AVIF  🖼 `);
      }
      const buf = await encodeImage(img, format, { quality });
      const relOut = await resolveOutPath(rel, EXT_OF[format] ?? format, o);
      await host.fs.write(relOut, buf);
      return { out: pretty(host.cwd, relOut), outRel: relOut, bytes: buf.length };
    }
    async function processOne(rel, plan, o) {
      const { buf: srcBuf, format: srcFormat, img: src } = await loadImage(rel);
      let img = src;
      const steps = [];
      if (plan.rotate) {
        img = rotateImage(img, Number(plan.rotate));
        steps.push(` ${Number(plan.rotate)}°`);
      }
      if (plan.flip) {
        img = flipImage(img, String(plan.flip));
        steps.push(` ${plan.flip}`);
      }
      if (plan.angle) {
        const bg = parseColor(plan.background) ?? [0, 0, 0, 0];
        img = rotateArbitrary(img, Number(plan.angle), { background: bg });
        steps.push(` ${Number(plan.angle)}°`);
      }
      if (plan.crop) {
        const c = plan.crop;
        img = cropImage(img, {
          x: Number(c.x ?? 0),
          y: Number(c.y ?? 0),
          width: Number(c.width ?? c.w ?? img.width),
          height: Number(c.height ?? c.h ?? img.height)
        });
        steps.push(` ${img.width}×${img.height}`);
      }
      if (plan.resize) {
        const r = plan.resize;
        const before = { w: img.width, h: img.height };
        const target = {};
        if (r.percent) {
          target.width = Math.max(1, Math.round(img.width * Number(r.percent) / 100));
          target.height = Math.max(1, Math.round(img.height * Number(r.percent) / 100));
        } else if (r.longEdge) {
          const le = Number(r.longEdge);
          if (img.width >= img.height) {
            target.width = le;
            target.height = Math.max(1, Math.round(img.height * le / img.width));
          } else {
            target.height = le;
            target.width = Math.max(1, Math.round(img.width * le / img.height));
          }
        } else {
          target.width = r.width ? Number(r.width) : void 0;
          target.height = r.height ? Number(r.height) : void 0;
        }
        const willUp = (target.width ?? img.width) > img.width || (target.height ?? img.height) > img.height;
        const exactBoth = Boolean(r.width && r.height);
        if (r.noUpscale === false || exactBoth || !willUp) {
          img = resizeImage(img, target);
          steps.push(` ${before.w}×${before.h} → ${img.width}×${img.height}`);
        }
      }
      if (plan.adjust && Object.keys(plan.adjust).length) {
        img = adjustImage(img, plan.adjust);
        steps.push(` ${Object.keys(plan.adjust).join("/")}`);
      }
      if (plan.watermarkPath) {
        const wmRel = normalizeRel(plan.watermarkPath);
        const { img: wm } = await loadImage(wmRel);
        const position = String(plan.position ?? "br");
        const opacity = plan.opacity === void 0 ? 0.8 : Number(plan.opacity);
        const scale = plan.scale === void 0 ? 1 : Number(plan.scale);
        const margin = Number(plan.margin ?? 0);
        const w = Math.max(1, Math.round(wm.width * scale));
        const h = Math.max(1, Math.round(wm.height * scale));
        const scaled = scale === 1 ? wm : resizeImage(wm, { width: w, height: h });
        const pos = {
          tl: [margin, margin],
          tc: [Math.round((img.width - w) / 2), margin],
          tr: [img.width - w - margin, margin],
          ml: [margin, Math.round((img.height - h) / 2)],
          center: [Math.round((img.width - w) / 2), Math.round((img.height - h) / 2)],
          mr: [img.width - w - margin, Math.round((img.height - h) / 2)],
          bl: [margin, img.height - h - margin],
          bc: [Math.round((img.width - w) / 2), img.height - h - margin],
          br: [img.width - w - margin, img.height - h - margin]
        }[position] ?? [img.width - w - margin, img.height - h - margin];
        img = compositeOverlay(img, scaled, {
          x: pos[0],
          y: pos[1],
          opacity,
          tile: Boolean(plan.tile),
          gap: Number(plan.gap ?? 8)
        });
        steps.push(` ${wmRel} @${position}`);
      }
      const format = String(o.format ?? cfg.defaultFormat ?? "keep");
      const outFormat = !format || format === "keep" ? SERVER_ENCODE.has(srcFormat) ? srcFormat : "png" : format;
      const quality = Math.round(Math.min(1, Math.max(0.05, Number(o.quality ?? cfg.quality ?? 0.82))) * 100);
      const written = await writeImage(img, outFormat, quality, rel, o);
      return {
        in: pretty(host.cwd, rel),
        out: written.out,
        srcFormat,
        outFormat: outFormat === "jpeg" ? "jpeg" : outFormat,
        srcBytes: srcBuf.length,
        bytes: written.bytes,
        srcSize: `${src.width}×${src.height}`,
        size: `${img.width}×${img.height}`,
        outRel: written.outRel,
        steps
      };
    }
    async function processMany(rels, plan, o) {
      const results = [];
      for (const rel of rels) {
        try {
          results.push(await processOne(rel, plan, o));
        } catch (err) {
          results.push({ in: pretty(host.cwd, rel), error: err instanceof Error ? err.message : String(err) });
        }
      }
      return results;
    }
    function summarize(results, title) {
      const ok = results.filter((r) => !r.error);
      const bad = results.filter((r) => r.error);
      const lines = [title];
      for (const r of ok) {
        const saved = r.srcBytes && r.bytes ? ` (${fmtBytes(r.srcBytes)} → ${fmtBytes(r.bytes)})` : "";
        const ratio = r.srcBytes && r.bytes ? ` ${Math.round((1 - r.bytes / r.srcBytes) * 100)}%↓` : "";
        lines.push(`✅ ${r.in} → ${r.out}  ${r.srcSize} → ${r.size}  ${r.outFormat}${saved}${ratio}`);
      }
      for (const r of bad) lines.push(`❌ ${r.in}: ${r.error}`);
      return lines.join("\n");
    }
    const TOOLS = [
      {
        name: "image_info",
        label: "",
        description: "Inspect images in the workspace: format, pixel size, aspect ratio, file bytes, alpha, EXIF (camera/exposure/GPS), plus histogram/dominant colors on request. Use it before compressing or cropping so you know what you are dealing with. Accepts one path, several paths, or a directory to scan. ////EXIF",
        promptSnippet: "image_info — inspect workspace image metadata (size/format/EXIF), also scans a directory",
        promptGuidelines: [
          "Before compressing or cropping an image, call image_info to learn its real dimensions and format.",
          "image_info accepts a directory to list every image inside (useful for bulk work)."
        ],
        parameters: {
          type: "object",
          properties: {
            path: { type: "string", description: "Image path relative to the workspace (or absolute inside it)." },
            paths: { type: "array", items: { type: "string" }, description: "Several image paths at once." },
            dir: { type: "string", description: "Directory to scan recursively for images (max depth 3, 200 files)." },
            details: {
              type: "boolean",
              description: "Also compute histogram peaks and dominant colors (slower, decodes pixels)."
            }
          }
        },
        async execute(_id, params) {
          const rels0 = pathList(params);
          const dir = typeof params.dir === "string" ? normalizeRel(params.dir) : "";
          if (typeof params.dir === "string") {
            const found = await scanImages(dir, 0, []);
            for (const f of found) if (!rels0.includes(f)) rels0.push(f);
          }
          const rels = rels0;
          if (!rels.length) {
            const entries = await listDir("");
            const imgs = entries.filter((e) => e.isImage).map((e) => e.path);
            return ` path/paths/dir${imgs.length ? imgs.join(", ") : ""}`;
          }
          const rows = [];
          for (const rel of rels) {
            try {
              const buf = await host.fs.read(rel);
              const p = probeImage(buf);
              const row = {
                path: pretty(host.cwd, rel),
                format: p.format,
                size: p.width && p.height ? `${p.width}×${p.height}` : "?",
                megapixels: p.megapixels,
                aspect: p.aspect ? Number(p.aspect.toFixed(4)) : null,
                bytes: buf.length,
                humanBytes: fmtBytes(buf.length),
                alpha: p.hasAlpha,
                animated: p.animated ?? void 0,
                serverEditable: SERVER_DECODE.has(p.format),
                exif: parseExif(buf) ?? void 0
              };
              if (params.details && SERVER_DECODE.has(p.format)) {
                if (p.format === "jpeg" && !await ensureJpeg()) {
                  row.detailsError = " jpeg-js  JPEG ";
                } else {
                  const img = await decodeImage(buf, { maxPixels: MAX_PIXELS });
                  const h = histogram(img);
                  row.histogramPeak = {
                    r: h.r.indexOf(Math.max(...h.r)),
                    g: h.g.indexOf(Math.max(...h.g)),
                    b: h.b.indexOf(Math.max(...h.b))
                  };
                  row.dominantColors = dominantColors(img, 5).map((c) => ({
                    hex: `#${c.rgb.map((v) => v.toString(16).padStart(2, "0")).join("")}`,
                    share: Number(c.share.toFixed(3))
                  }));
                }
              }
              rows.push(row);
            } catch (err) {
              rows.push({ path: pretty(host.cwd, rel), error: err instanceof Error ? err.message : String(err) });
            }
          }
          return { content: [{ type: "text", text: JSON.stringify(rows, null, 2) }], details: { count: rows.length } };
        }
      },
      {
        name: "image_transform",
        label: "/",
        description: "Transform workspace images: resize (width/height/longEdge/percent), crop, rotate 90/arbitrary, flip, and per-pixel adjust (brightness/contrast/saturation/hue/gamma/grayscale/sepia/invert/blur/sharpen/vignette). Writes new files (never overwrites unless asked). Supports batch via `paths`. PNG/JPEG/BMP only — WebP/GIF/AVIF belong in the 🖼 view. //// PNG/JPEG/BMP",
        promptSnippet: "image_transform — resize / crop / rotate / flip / adjust workspace images (PNG/JPEG/BMP, batch ok)",
        promptGuidelines: [
          "image_transform never overwrites the source unless overwrite=true; by default it writes <name><suffix>.<ext> next to the original (or into outDir).",
          "Crop coordinates from image_info are 1:1 pixels of the *current* file; if you also rotate, crop applies after rotation.",
          "For 'make the long edge 1600px' use resize.longEdge=1600 (noUpscale defaults to true).",
          "Passing both resize.width and resize.height means exact dimensions — that overrides the no-upscale default."
        ],
        parameters: {
          type: "object",
          properties: {
            path: { type: "string", description: "Image path (relative to workspace)." },
            paths: {
              type: "array",
              items: { type: "string" },
              description: "Batch: several images with the same plan."
            },
            resize: {
              type: "object",
              description: "Resize. Give one of: width/height (px), longEdge (px, the longer side), percent (%).",
              properties: {
                width: { type: "number" },
                height: { type: "number" },
                longEdge: { type: "number" },
                percent: { type: "number" },
                noUpscale: {
                  type: "boolean",
                  description: "Default true: never enlarge beyond the source. Ignored when both width and height are given."
                }
              }
            },
            crop: {
              type: "object",
              description: "Crop rectangle in pixels of the rotated image (top-left origin).",
              properties: {
                x: { type: "number" },
                y: { type: "number" },
                width: { type: "number" },
                height: { type: "number" }
              }
            },
            rotate: { type: "number", description: "90/180/270 (clockwise degrees)." },
            flip: { type: "string", enum: ["h", "v"], description: "Horizontal or vertical mirror." },
            angle: {
              type: "number",
              description: "Arbitrary rotation in degrees (canvas expands, background param fills)."
            },
            background: {
              type: "string",
              description: "Fill for arbitrary rotation, e.g. #ffffff or #ffffff00 (default transparent)."
            },
            adjust: {
              type: "object",
              description: "Per-pixel adjustments. Percentages default to 100 (=unchanged), strength fields 0..100.",
              properties: {
                brightness: { type: "number" },
                contrast: { type: "number" },
                saturation: { type: "number" },
                hue: { type: "number", description: "Degrees, -180..180" },
                gamma: { type: "number" },
                grayscale: { type: "number" },
                sepia: { type: "number" },
                invert: { type: "number" },
                blur: { type: "number", description: "0..50 px radius" },
                sharpen: { type: "number" },
                vignette: { type: "number" }
              }
            },
            format: {
              type: "string",
              enum: ["png", "jpeg", "bmp", "keep"],
              description: "Output format (default: plugin setting / keep)."
            },
            quality: { type: "number", description: "JPEG quality 0.1..1 (ignored by PNG/BMP)." },
            out: { type: "string", description: "Explicit output path (single file only)." },
            outDir: { type: "string", description: "Directory for outputs (created if missing)." },
            suffix: { type: "string", description: "Filename suffix (default from plugin settings, e.g. -min)." },
            overwrite: { type: "boolean", description: "Allow replacing an existing file." }
          }
        },
        async execute(_id, params) {
          const rels = pathList(params);
          if (!rels.length) throw new Error(" path paths");
          if (rels.length > 1 && params.out) throw new Error(" out outDir + suffix");
          const results = await processMany(rels, params, params);
          return { content: [{ type: "text", text: summarize(results, ` ${results.length} `) }], details: { results } };
        }
      },
      {
        name: "image_compress",
        label: "",
        description: "Compress workspace images: convert format (png/jpeg/bmp) and/or hit a target file size with a quality binary search (plus downscaling when quality alone is not enough). Use `targetKB` for 'under 300 KB' requests and `quality` for a fixed quality. Batch via `paths`.  + ",
        promptSnippet: "image_compress — shrink workspace images to a quality or a target file size (batch ok)",
        promptGuidelines: [
          "To hit a size budget, pass targetKB — do not guess quality by hand, the tool binary-searches it.",
          "Compressing a PNG meaningfully usually means converting to jpeg or webp; jpeg is what the server can write (webp only in the 🖼 view)."
        ],
        parameters: {
          type: "object",
          properties: {
            path: { type: "string" },
            paths: { type: "array", items: { type: "string" } },
            quality: { type: "number", description: "JPEG quality 0.1..1 (default from settings, usually 0.82)." },
            targetKB: { type: "number", description: "Desired maximum file size in KB. Overrides quality." },
            format: {
              type: "string",
              enum: ["jpeg", "png", "bmp", "keep"],
              description: "Output format (default jpeg when compressing)."
            },
            maxLongEdge: {
              type: "number",
              description: "Optional cap on the longer side in px (applied before encoding)."
            },
            outDir: { type: "string" },
            suffix: { type: "string" },
            overwrite: { type: "boolean" }
          }
        },
        async execute(_id, params) {
          const rels = pathList(params);
          if (!rels.length) throw new Error(" path paths");
          const o = { ...params, format: params.format ?? "jpeg" };
          const targetBytes = params.targetKB ? Number(params.targetKB) * 1024 : 0;
          const results = [];
          for (const rel of rels) {
            try {
              const { buf, format: srcFormat, img: src } = await loadImage(rel);
              let img = src;
              if (params.maxLongEdge) {
                const le = Number(params.maxLongEdge);
                const w = img.width >= img.height ? le : Math.round(img.width * le / img.height);
                const h = img.width >= img.height ? Math.round(img.height * le / img.width) : le;
                if (w < img.width || h < img.height) img = resizeImage(img, { width: w, height: h });
              }
              const outFormat = String(o.format) === "keep" ? SERVER_ENCODE.has(srcFormat) ? srcFormat : "jpeg" : String(o.format);
              if (!SERVER_ENCODE.has(outFormat)) throw new Error(` ${outFormat}`);
              if (outFormat === "jpeg" && !await ensureJpeg()) throw new Error(" jpeg-js JS ");
              if (!SERVER_ENCODE.has(srcFormat) && srcFormat === "jpeg") await ensureJpeg();
              let quality = Math.round(Math.min(1, Math.max(0.1, Number(params.quality ?? cfg.quality ?? 0.82))) * 100);
              let encoded = await encodeImage(img, outFormat, { quality });
              let usedQuality = quality;
              if (targetBytes > 0 && outFormat === "jpeg") {
                let lo = 10;
                let hi = 100;
                let best = null;
                for (let i = 0; i < 7; i++) {
                  const mid = Math.round((lo + hi) / 2);
                  const candidate = await encodeImage(img, outFormat, { quality: mid });
                  if (candidate.length <= targetBytes) {
                    best = { buf: candidate, q: mid };
                    lo = mid + 1;
                  } else {
                    hi = mid - 1;
                  }
                  if (lo > hi) break;
                }
                if (!best) {
                  const shrink = Math.sqrt(targetBytes / encoded.length);
                  const w = Math.max(1, Math.round(img.width * shrink * 0.98));
                  const h = Math.max(1, Math.round(img.height * shrink * 0.98));
                  img = resizeImage(img, { width: w, height: h });
                  encoded = await encodeImage(img, outFormat, { quality: 60 });
                  best = { buf: encoded, q: 60 };
                }
                encoded = best.buf;
                usedQuality = best.q;
              }
              const relOut = await resolveOutPath(rel, EXT_OF[outFormat] ?? outFormat, params);
              await host.fs.write(relOut, encoded);
              results.push({
                in: pretty(host.cwd, rel),
                out: pretty(host.cwd, relOut),
                outRel: relOut,
                srcFormat,
                outFormat,
                srcSize: `${src.width}×${src.height}`,
                size: `${img.width}×${img.height}`,
                srcBytes: buf.length,
                bytes: encoded.length,
                quality: usedQuality
              });
            } catch (err) {
              results.push({ in: pretty(host.cwd, rel), error: err instanceof Error ? err.message : String(err) });
            }
          }
          return { content: [{ type: "text", text: summarize(results, ` ${results.length} `) }], details: { results } };
        }
      },
      {
        name: "image_watermark",
        label: "",
        description: "Stamp an image (logo/PNG with alpha) onto workspace images: 9-grid position, opacity, scale, margin, or full tiling. Text watermarks with real fonts are browser-side only (🖼 view). logo",
        promptSnippet: "image_watermark — overlay a logo image onto workspace images (position/opacity/tile)",
        promptGuidelines: [
          "image_watermark takes an image overlay, not text — for text watermarks tell the user to use the 🖼 view (real fonts are browser-side).",
          'A watermarked output defaults to <name>-wm.<ext> next to the source if you pass suffix="-wm".'
        ],
        parameters: {
          type: "object",
          properties: {
            path: { type: "string" },
            paths: { type: "array", items: { type: "string" } },
            watermarkPath: { type: "string", description: "Overlay image path (PNG with alpha works best)." },
            position: {
              type: "string",
              enum: ["tl", "tc", "tr", "ml", "center", "mr", "bl", "bc", "br"],
              description: "Default br."
            },
            opacity: { type: "number", description: "0..1, default 0.8" },
            scale: { type: "number", description: "Overlay scale factor, default 1." },
            margin: { type: "number", description: "Margin in px from the edges (ignored when tiling)." },
            tile: { type: "boolean", description: "Tile the overlay across the whole image." },
            gap: { type: "number", description: "Tile spacing in px, default 8." },
            suffix: { type: "string", description: "Default -wm." },
            outDir: { type: "string" },
            overwrite: { type: "boolean" }
          },
          required: ["watermarkPath"]
        },
        async execute(_id, params) {
          const rels = pathList(params);
          if (!rels.length) throw new Error(" path paths");
          if (!params.watermarkPath) throw new Error(" watermarkPath");
          const o = { ...params, suffix: params.suffix ?? "-wm" };
          const results = await processMany(rels, { watermarkPath: params.watermarkPath, ...params }, o);
          return { content: [{ type: "text", text: summarize(results, ` ${results.length} `) }], details: { results } };
        }
      }
    ];
    function syncTools() {
      const want = cfg.aiTools !== false;
      if (want === toolsOn) return;
      if (want) {
        offTools = TOOLS.map((t) => host.registerAgentTool(t));
        toolsOn = true;
        host.log(`AI ${TOOLS.map((t) => t.name).join(", ")}`);
      } else {
        for (const off of offTools) {
          try {
            off();
          } catch {
          }
        }
        offTools = [];
        toolsOn = false;
        host.log("AI ");
      }
    }
    syncTools();
    const offSettings = host.onSettingsChanged?.((v) => {
      cfg = v ?? {};
      host.broadcast({ kind: "settings", values: cfg });
      syncTools();
    });
    async function readBody(req) {
      const b = req.body;
      if (b && typeof b === "object" && typeof b.dataBase64 === "string") {
        return Buffer.from(b.dataBase64, "base64");
      }
      const chunks = [];
      for await (const c of req) chunks.push(Buffer.isBuffer(c) ? c : Buffer.from(c));
      return Buffer.concat(chunks);
    }
    function safeRoute(method, path, handler) {
      return host.route(method, path, async (req, res) => {
        try {
          await handler(req, res);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          host.log(`http ${method} ${path} `, err);
          if (!res.headersSent) res.status(400).json({ error: msg });
          else res.end();
        }
      });
    }
    const offList = safeRoute("GET", "/ws/list", async (req, res) => {
      const dir = normalizeRel(req.query?.dir);
      res.json({ cwd: host.cwd, dir, entries: await listDir(dir) });
    });
    const offImage = safeRoute("GET", "/ws/image", async (req, res) => {
      const rel = normalizeRel(req.query?.path);
      if (!rel) {
        res.status(400).json({ error: " path" });
        return;
      }
      const buf = await host.fs.read(rel);
      res.setHeader("Cache-Control", "no-store");
      res.type(mimeForFormat(sniffFormat(buf))).send(buf);
    });
    const offProbe = safeRoute("GET", "/ws/probe", async (req, res) => {
      const rel = normalizeRel(req.query?.path);
      if (!rel) {
        res.status(400).json({ error: " path" });
        return;
      }
      const buf = await host.fs.read(rel);
      const p = probeImage(buf);
      res.json({
        path: rel,
        name: basename(rel),
        bytes: buf.length,
        ...p,
        exif: parseExif(buf),
        serverEditable: SERVER_DECODE.has(p.format)
      });
    });
    const offSave = safeRoute("POST", "/ws/save", async (req, res) => {
      const rel = normalizeRel(req.query?.path);
      if (!rel) {
        res.status(400).json({ error: " path" });
        return;
      }
      const data = await readBody(req);
      if (!data.length) {
        res.status(400).json({ error: "" });
        return;
      }
      const overwrite = String(req.query?.overwrite ?? "") === "1";
      const relOut = overwrite ? rel : await resolveOutPath(rel, extname(rel).replace(/^\./, "") || "bin", {
        outDir: normalizeRel(dirname(rel)),
        suffix: ""
      });
      await host.fs.write(relOut, data);
      host.log(` ${pretty(host.cwd, relOut)}${fmtBytes(data.length)}`);
      res.json({
        ok: true,
        path: relOut,
        pretty: pretty(host.cwd, relOut),
        bytes: data.length,
        renamed: relOut !== rel
      });
    });
    const offSettingsRoute = safeRoute("GET", "/ws/settings", async (_req, res) => {
      res.json({ cwd: host.cwd, settings: cfg, serverFormats: [...SERVER_ENCODE] });
    });
    host.log(` ${host.cwd}AI  ${cfg.aiTools === false ? "" : ""}`);
    return () => {
      for (const off of [offList, offImage, offProbe, offSave, offSettingsRoute, offSettings]) {
        try {
          off?.();
        } catch {
        }
      }
      for (const off of offTools) {
        try {
          off();
        } catch {
        }
      }
      offTools = [];
      host.log("");
    };
  }
};
export {
  index_default as default
};
