/* Generated by scripts/build-plugins.mjs from plugins/jira-review/src/index.ts - do not edit. */

// plugins/jira-review/src/jira-api.ts
var BOARD_ID_RE = /^\d+$/;
var ISSUE_KEY_RE = /^[A-Z][A-Z0-9_]*-\d+$/i;
function normalizeSiteUrl(value) {
  if (typeof value !== "string" || !value.trim()) throw new Error("Site URL is required");
  let url;
  try {
    url = new URL(value.trim());
  } catch {
    throw new Error("Site URL must be a valid HTTPS URL");
  }
  if (url.protocol !== "https:") throw new Error("Site URL must use HTTPS");
  if (!url.hostname.toLowerCase().endsWith(".atlassian.net"))
    throw new Error("Site URL must be an Atlassian Cloud site");
  if (url.username || url.password || url.search || url.hash || url.pathname !== "/") {
    throw new Error("Site URL must not contain credentials, a path, a query, or a fragment");
  }
  return url.origin;
}
function requireBoardId(value) {
  const id = String(value ?? "").trim();
  if (!BOARD_ID_RE.test(id)) throw new Error("Board ID must be a number");
  return id;
}
function requireIssueKey(value) {
  const key = String(value ?? "").trim();
  if (!ISSUE_KEY_RE.test(key)) throw new Error("Issue key is invalid");
  return key;
}
function requireJql(value) {
  const jql = String(value ?? "").trim();
  if (!jql || jql.length > 4e3 || jql.includes("\0")) throw new Error("Ready JQL is invalid");
  return jql;
}
function requestError(status, statusText) {
  const suffix = statusText && /^[\w .-]{1,80}$/.test(statusText) ? ` ${statusText}` : "";
  return new Error(`Jira request failed (${status}${suffix})`);
}
async function requestJson(request, url, init) {
  let response;
  try {
    response = await request(url, init);
  } catch {
    throw new Error("Jira request failed (network error)");
  }
  if (!response.ok) throw requestError(response.status, response.statusText);
  if (response.status === 204) return {};
  try {
    return await response.json();
  } catch {
    throw new Error("Jira returned an invalid response");
  }
}
function createJiraApi(siteUrl, email, token, request = fetch) {
  const base = normalizeSiteUrl(siteUrl);
  if (!email.trim() || !email.includes("@")) throw new Error("Jira email is invalid");
  if (!token.trim()) throw new Error("Jira API token is required");
  const auth = `Basic ${Buffer.from(`${email}:${token}`).toString("base64")}`;
  const headers = { Authorization: auth, Accept: "application/json" };
  const json = (path, init = {}) => requestJson(request, `${base}${path}`, { ...init, headers: { ...headers, ...init.headers } });
  return {
    async activeSprint(boardId) {
      const body = await json(`/rest/agile/1.0/board/${requireBoardId(boardId)}/sprint?state=active`);
      const values = body.values;
      if (!Array.isArray(values)) return null;
      const sprint = values.find((item) => {
        return !!item && typeof item === "object" && Number.isInteger(Number(item.id));
      });
      if (!sprint) return null;
      return {
        id: Number(sprint.id),
        name: typeof sprint.name === "string" ? sprint.name : `Sprint ${sprint.id}`,
        state: typeof sprint.state === "string" ? sprint.state : "active"
      };
    },
    async searchIssues(sprintId, readyJql) {
      if (!Number.isInteger(sprintId) || sprintId < 0) throw new Error("Sprint ID is invalid");
      const jql = `sprint = ${sprintId} AND (${requireJql(readyJql)})`;
      const issues = [];
      const pageSize = 100;
      let nextPageToken;
      for (; ; ) {
        const params = new URLSearchParams({
          jql,
          fields: "summary,status,assignee,labels,description",
          maxResults: String(pageSize)
        });
        if (nextPageToken) params.set("nextPageToken", nextPageToken);
        const body = await json(`/rest/api/3/search/jql?${params}`);
        const page = Array.isArray(body.issues) ? body.issues ?? [] : [];
        issues.push(...page);
        const next = body.nextPageToken;
        if (!page.length || body.isLast === true || typeof next !== "string" || !next)
          return issues;
        nextPageToken = next;
      }
    },
    async postComment(issueKey, comment) {
      const text = String(comment ?? "").trim();
      if (!text || text.length > 2e4) throw new Error("Comment is invalid");
      await json(`/rest/api/3/issue/${encodeURIComponent(requireIssueKey(issueKey))}/comment`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          body: { type: "doc", version: 1, content: [{ type: "paragraph", content: [{ type: "text", text }] }] }
        })
      });
    },
    async addLabel(issueKey, label) {
      const safeLabel = String(label ?? "").trim();
      if (!safeLabel || !/^[\w-]+$/.test(safeLabel)) throw new Error("Label is invalid");
      await json(`/rest/api/3/issue/${encodeURIComponent(requireIssueKey(issueKey))}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ update: { labels: [{ add: safeLabel }] } })
      });
    }
  };
}

// plugins/jira-review/src/index.ts
var CONFIG_KEY = "jira-review.config";
var REVIEWS_KEY = "jira-review.reviews";
var TAG = "dogits-dans-le-nez";
var DEFAULT_READY_JQL = 'assignee IS EMPTY AND statusCategory = "To Do"';
var ISSUE_KEY_RE2 = /^[A-Z][A-Z0-9_]*-\d+$/i;
function textFromDescription(value) {
  if (typeof value === "string") return value;
  if (!value || typeof value !== "object") return "";
  const item = value;
  if (typeof item.text === "string") return item.text;
  if (!Array.isArray(item.content)) return "";
  return item.content.map(textFromDescription).filter(Boolean).join(" ");
}
function normalizeIssue(issue) {
  if (!issue || typeof issue.key !== "string" || !issue.key.trim()) return null;
  const fields = issue.fields ?? {};
  const status = fields.status;
  const assignee = fields.assignee;
  const assigneeName = assignee && typeof assignee === "object" ? assignee.displayName ?? assignee.emailAddress : null;
  const labels = Array.isArray(fields.labels) ? fields.labels.filter((label) => typeof label === "string") : [];
  return {
    ...typeof issue.id === "string" ? { id: issue.id } : {},
    key: issue.key.trim(),
    summary: typeof fields.summary === "string" ? fields.summary : "",
    description: textFromDescription(fields.description),
    status: status && typeof status === "object" && typeof status.name === "string" ? status.name : "",
    assignee: typeof assigneeName === "string" ? assigneeName : null,
    labels
  };
}
function isRecord(value) {
  return !!value && typeof value === "object" && !Array.isArray(value);
}
function validateConfig(value) {
  if (!isRecord(value)) throw new Error("Jira configuration is required");
  const siteUrl = normalizeSiteUrl(String(value.siteUrl ?? ""));
  const email = String(value.email ?? "").trim();
  const boardId = String(value.boardId ?? "").trim();
  const readyJql = String(value.readyJql ?? "").trim() || DEFAULT_READY_JQL;
  if (!email || !email.includes("@") || email.length > 320) throw new Error("Jira email is invalid");
  if (!/^\d+$/.test(boardId)) throw new Error("Board ID must be a number");
  if (!readyJql || readyJql.length > 4e3 || readyJql.includes("\0")) throw new Error("Ready JQL is invalid");
  return { siteUrl, email, boardId, readyJql };
}
function validateStringList(value, name) {
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string"))
    return `${name} must be a list of strings`;
  return null;
}
function validateReview(value) {
  if (!isRecord(value)) return "Review must be an object";
  for (const field of ["rationale", "draftComment"]) {
    if (typeof value[field] !== "string" || !value[field].trim()) return `${field} is required`;
  }
  if (typeof value.ready !== "boolean") return "ready must be boolean";
  if (value.difficulty !== "easy" && value.difficulty !== "medium" && value.difficulty !== "hard") {
    return "difficulty must be easy, medium, or hard";
  }
  if (value.confidence !== "high" && value.confidence !== "medium" && value.confidence !== "low") {
    return "confidence must be high, medium, or low";
  }
  for (const field of ["missingInfo", "implementationPlan", "confidenceSuggestions"]) {
    const error = validateStringList(value[field], field);
    if (error) return error;
  }
  return null;
}
function asReview(value) {
  return value;
}
function reviewScope(config) {
  return config?.siteUrl ?? "_unconfigured";
}
function loadReviewStore(value) {
  if (!isRecord(value)) return {};
  const entries = Object.entries(value);
  const legacy = entries.filter(([key, review]) => ISSUE_KEY_RE2.test(key) && validateReview(review) === null);
  if (entries.length > 0 && legacy.length === entries.length) {
    return { _unconfigured: Object.fromEntries(legacy) };
  }
  const store = {};
  for (const [scope, raw] of entries) {
    if (!isRecord(raw)) continue;
    const valid = Object.fromEntries(
      Object.entries(raw).filter(([key, review]) => ISSUE_KEY_RE2.test(key) && validateReview(review) === null)
    );
    if (Object.keys(valid).length > 0) store[scope] = valid;
  }
  return store;
}
function publicState(config, activeSprint, tickets, reviews, folders, error) {
  return { configured: !!config, config, activeSprint, tickets, reviews, folders, ...error ? { error } : {} };
}
function errorText(error) {
  return error instanceof Error && error.message ? error.message : "Jira operation failed";
}
var index_default = {
  activate(host) {
    let config = (() => {
      try {
        const stored = host.storage.get(CONFIG_KEY);
        return stored ? validateConfig(stored) : null;
      } catch {
        return null;
      }
    })();
    let activeSprint = null;
    let tickets = [];
    let folders = [];
    let error;
    let reviewStore = loadReviewStore(host.storage.get(REVIEWS_KEY, {}));
    const currentReviews = () => reviewStore[reviewScope(config)] ?? {};
    const sendState = (clientId) => {
      const payload = {
        kind: "state",
        state: publicState(config, activeSprint, tickets, currentReviews(), folders, error)
      };
      host.broadcast(payload);
      if (clientId) host.sendTo(clientId, payload);
    };
    const sendResult = (clientId, result) => {
      if (clientId) host.sendTo(clientId, { kind: "result", ...result });
    };
    const getToken = () => {
      const token = host.secrets.get("jira_api_token");
      if (!token?.trim()) throw new Error("Jira API token is not configured");
      return token;
    };
    const storeToken = (token) => {
      try {
        host.secrets.set("jira_api_token", token);
      } catch {
        throw new Error("Jira API token could not be stored securely");
      }
      if (host.secrets.get("jira_api_token") !== token) throw new Error("Jira API token could not be stored securely");
    };
    const getApi = () => {
      if (!config) throw new Error("Jira is not configured");
      return createJiraApi(config.siteUrl, config.email, getToken());
    };
    const refresh = async (clientId) => {
      try {
        if (!config) throw new Error("Jira is not configured");
        const api = getApi();
        activeSprint = await api.activeSprint(config.boardId);
        tickets = activeSprint ? (await api.searchIssues(activeSprint.id, config.readyJql)).map(normalizeIssue).filter((ticket) => !!ticket) : [];
        try {
          folders = (await host.fs.list()).filter((entry) => entry.type === "dir").map((entry) => entry.name);
        } catch {
          folders = [];
        }
        error = void 0;
      } catch (err) {
        error = errorText(err);
      }
      sendState(clientId);
    };
    const saveReview = (key, value) => {
      if (typeof key !== "string" || !ISSUE_KEY_RE2.test(key.trim())) throw new Error("Issue key is invalid");
      const reviewError = validateReview(value);
      if (reviewError) throw new Error(reviewError);
      const normalizedKey = key.trim();
      const scope = reviewScope(config);
      reviewStore = { ...reviewStore, [scope]: { ...currentReviews(), [normalizedKey]: asReview(value) } };
      host.storage.set(REVIEWS_KEY, reviewStore);
      return { ok: true, key: normalizedKey };
    };
    const offMessage = host.onMessage(async (payload, from) => {
      const message = isRecord(payload) ? payload : {};
      try {
        switch (message.action) {
          case "get_state":
            sendState(from);
            break;
          case "save_config": {
            const next = validateConfig(message.config);
            const token = typeof message.token === "string" ? message.token.trim() : "";
            if (token) storeToken(token);
            else if (!host.secrets.get("jira_api_token")?.trim()) throw new Error("Jira API token is required");
            host.storage.set(CONFIG_KEY, next);
            config = next;
            error = void 0;
            sendResult(from, { ok: true, action: "save_config" });
            sendState(from);
            break;
          }
          case "refresh":
            await refresh(from);
            break;
          case "save_review":
            sendResult(from, { action: "save_review", ...saveReview(message.key, message.review) });
            sendState(from);
            break;
          case "post_review": {
            const api = getApi();
            await api.postComment(String(message.key ?? ""), String(message.comment ?? ""));
            try {
              await api.addLabel(String(message.key ?? ""), TAG);
              host.notify("info", "Jira review posted and labeled");
              sendResult(from, { ok: true, action: "post_review", key: message.key });
            } catch (labelError) {
              host.notify("warning", `Jira review posted, but label update failed: ${errorText(labelError)}`);
              sendResult(from, {
                ok: true,
                action: "post_review",
                key: message.key,
                labelOk: false,
                labelError: errorText(labelError)
              });
            }
            break;
          }
        }
      } catch (err) {
        error = errorText(err);
        sendResult(from, { ok: false, action: message.action, error });
        sendState(from);
      }
    });
    const offAttach = host.onAttach?.((clientId) => sendState(clientId));
    const offTool = host.registerAgentTool({
      name: "jira_review_save",
      description: "Save a complete Jira ticket review without posting to Jira.",
      parameters: {
        type: "object",
        properties: {
          key: { type: "string" },
          review: {
            type: "object",
            properties: {
              ready: { type: "boolean" },
              difficulty: { enum: ["easy", "medium", "hard"] },
              confidence: { enum: ["high", "medium", "low"] },
              rationale: { type: "string" },
              missingInfo: { type: "array", items: { type: "string" } },
              implementationPlan: { type: "array", items: { type: "string" } },
              draftComment: { type: "string" },
              confidenceSuggestions: { type: "array", items: { type: "string" } }
            }
          }
        },
        required: ["key", "review"]
      },
      execute: async (_id, params) => {
        const result = saveReview(params.key, params.review);
        sendState();
        return result;
      }
    });
    return () => {
      offMessage();
      offAttach?.();
      offTool();
    };
  }
};
export {
  CONFIG_KEY,
  DEFAULT_READY_JQL,
  REVIEWS_KEY,
  TAG,
  index_default as default,
  normalizeIssue,
  validateReview
};
