/* Generated by scripts/build-plugins.mjs from plugins/worktree-preparer/src/client.ts - do not edit. */

// plugins/worktree-preparer/src/client.ts
function record(value) {
  return value && typeof value === "object" ? value : null;
}
function stateFrom(payload) {
  const outer = record(payload);
  const value = record(outer?.state) ?? outer;
  if (!value || value.kind !== void 0 && value.kind !== "state") return null;
  return {
    cwd: typeof value.cwd === "string" ? value.cwd : "",
    folders: Array.isArray(value.folders) ? value.folders.filter((folder) => typeof folder === "string") : [],
    result: value.result ?? null,
    error: typeof value.error === "string" ? value.error : null
  };
}
function field(document, name, type = "text") {
  const input = document.createElement("input");
  input.type = type;
  input.dataset.field = name;
  return input;
}
var client_default = {
  mount(container, ctx) {
    const document = container?.ownerDocument;
    if (!document || typeof container.replaceChildren !== "function") return () => {
    };
    let current = { cwd: "", folders: [], result: null, error: null };
    let branch;
    let outputName;
    let selections = [];
    const render = () => {
      const heading = document.createElement("h3");
      heading.textContent = "Prepare worktrees";
      const cwd = document.createElement("p");
      cwd.textContent = current.cwd;
      branch = field(document, "branch");
      branch.value = "agent/";
      outputName = field(document, "outputName");
      outputName.value = ".pi/projects/new-project";
      selections = current.folders.map((folder) => {
        const input = field(document, "selection", "checkbox");
        input.value = folder;
        return input;
      });
      const prepare = document.createElement("button");
      prepare.type = "button";
      prepare.dataset.action = "prepare";
      prepare.textContent = "Prepare";
      prepare.addEventListener("click", () => {
        ctx.send({
          action: "prepare",
          branch: branch.value,
          outputName: outputName.value,
          selections: selections.filter((selection) => selection.checked).map((selection) => selection.value)
        });
      });
      const status = document.createElement("p");
      status.dataset.field = "result";
      status.textContent = current.result ? JSON.stringify(current.result) : "";
      const error = document.createElement("p");
      error.dataset.field = "error";
      error.textContent = current.error ?? "";
      container.replaceChildren(heading, cwd, branch, outputName, ...selections, prepare, status, error);
    };
    render();
    const unsubscribe = ctx.onData((payload) => {
      const next = stateFrom(payload);
      if (next) {
        current = next;
        render();
      }
    });
    ctx.send({ action: "get_state" });
    return () => {
      unsubscribe();
      container.replaceChildren();
    };
  }
};
export {
  client_default as default
};
