/* Generated by scripts/build-plugins.mjs from plugins/mcp-manager/src/client.ts - do not edit. */

// plugins/mcp-manager/src/client.ts
var STYLES = `
.mcp-manager { padding: 12px; color: inherit; font: 13px/1.5 ui-sans-serif, system-ui, sans-serif; }
.mcp-manager h3 { margin: 0 0 4px; font-size: 15px; }
.mcp-manager h4 { margin: 0 0 6px; font-size: 13px; }
.mcp-manager .hint { margin: 0 0 10px; opacity: 0.75; }
.mcp-manager code { padding: 0 4px; border-radius: 3px; background: rgba(127, 127, 127, 0.18); }
.mcp-manager section { margin-top: 18px; }
.mcp-manager table { width: 100%; border-collapse: collapse; }
.mcp-manager th, .mcp-manager td { padding: 4px 8px; border-bottom: 1px solid rgba(127, 127, 127, 0.25); text-align: left; vertical-align: top; }
.mcp-manager td.name { font-weight: 600; white-space: nowrap; }
.mcp-manager td.actions { white-space: nowrap; text-align: right; }
.mcp-manager .muted { opacity: 0.7; }
.mcp-manager .off { opacity: 0.55; }
.mcp-manager .error { margin: 6px 0; color: #e5484d; white-space: pre-wrap; }
.mcp-manager button { padding: 2px 8px; border: 1px solid rgba(127, 127, 127, 0.5); border-radius: 4px; background: rgba(127, 127, 127, 0.12); color: inherit; font: inherit; cursor: pointer; }
.mcp-manager button + button { margin-left: 6px; }
.mcp-manager form { display: grid; gap: 8px; max-width: 620px; }
.mcp-manager label { display: grid; gap: 2px; }
.mcp-manager input, .mcp-manager textarea { padding: 3px 6px; border: 1px solid rgba(127, 127, 127, 0.4); border-radius: 4px; background: rgba(127, 127, 127, 0.08); color: inherit; font: inherit; }
.mcp-manager ul { margin: 0; padding: 0; list-style: none; }
`;
function parseArgsText(text) {
  return text.split("\n").map((line) => line.trim()).filter((line) => line !== "");
}
function parseEnvText(text) {
  const env = {};
  const rejected = [];
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (trimmed === "") continue;
    const equals = trimmed.indexOf("=");
    const key = equals === -1 ? "" : trimmed.slice(0, equals).trim();
    if (key === "") {
      rejected.push(trimmed);
      continue;
    }
    env[key] = trimmed.slice(equals + 1).trim();
  }
  return { env, rejected };
}
function summarizeEntry(entry) {
  if (typeof entry.url === "string" && entry.url !== "") return entry.url;
  if (typeof entry.command === "string" && entry.command !== "") {
    const args = Array.isArray(entry.args) ? entry.args.filter((arg) => typeof arg === "string") : [];
    return [entry.command, ...args].join(" ");
  }
  return "(no command or url)";
}
function el(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== void 0) node.textContent = text;
  return node;
}
function button(label, onClick) {
  const node = el("button", void 0, label);
  node.type = "button";
  node.addEventListener("click", onClick);
  return node;
}
function appendField(form, labelText, input) {
  const label = el("label");
  label.append(el("span", "muted", labelText), input);
  form.append(label);
}
function describeSecrets(entry) {
  const parts = [];
  for (const field of ["env", "headers"]) {
    const record = entry[field];
    if (record && typeof record === "object") parts.push(`${field}: ${Object.keys(record).join(", ")}`);
  }
  if (typeof entry.bearerToken === "string") parts.push("bearer token set");
  return parts.join(" - ");
}
function serverRow(server, send) {
  const row = el("tr", server.disabled ? "off" : void 0);
  const name = el("td", "name", server.name);
  if (server.layers.length > 1) {
    name.append(" ", el("span", "muted", `(defined in ${server.layers.length} layers)`));
  }
  row.append(name);
  const definition = el("td");
  definition.append(el("div", void 0, summarizeEntry(server.entry)));
  const secrets = describeSecrets(server.entry);
  if (secrets !== "") definition.append(el("div", "muted", secrets));
  row.append(definition);
  const source = el("td", "muted");
  source.append(el("div", void 0, server.source.label));
  source.append(el("div", void 0, server.source.path));
  row.append(source);
  const status = el("td", void 0, server.disabled ? "disabled" : "enabled");
  row.append(status);
  const actions = el("td", "actions");
  actions.append(
    button(
      server.disabled ? "Enable" : "Disable",
      () => send({ action: "toggle", name: server.name, disabled: !server.disabled })
    )
  );
  if (server.source.writable) {
    actions.append(button("Remove", () => send({ action: "remove", name: server.name })));
  }
  row.append(actions);
  return row;
}
function serversSection(state, send) {
  const section = el("section");
  section.append(el("h4", void 0, `Servers (${state.servers.length})`));
  if (state.servers.length === 0) {
    section.append(
      el(
        "p",
        "muted",
        "No MCP servers are configured in any layer. Add one below, or run /mcp setup in pi to import from another tool."
      )
    );
    return section;
  }
  const table = el("table");
  const head = el("tr");
  for (const label of ["Server", "Definition", "Comes from", "State", ""]) head.append(el("th", void 0, label));
  table.append(head);
  for (const server of state.servers) table.append(serverRow(server, send));
  section.append(table);
  return section;
}
function addSection(send) {
  const section = el("section");
  section.append(el("h4", void 0, "Add a server"));
  section.append(el("p", "hint", "Written to the project Pi override, .pi/mcp.json."));
  const form = el("form");
  const error = el("div", "error");
  error.hidden = true;
  function textField(labelText, hint) {
    const input = document.createElement("input");
    input.type = "text";
    input.placeholder = hint;
    appendField(form, labelText, input);
    return input;
  }
  function areaField(labelText, hint) {
    const input = document.createElement("textarea");
    input.rows = 3;
    input.placeholder = hint;
    appendField(form, labelText, input);
    return input;
  }
  const name = textField("Name", "my-server");
  const command = textField("Command", "npx");
  const args = areaField("Arguments (one per line)", "-y\nsome-mcp-server");
  const url = textField("URL (remote server, leave empty for a command)", "https://example.com/mcp");
  const env = areaField("Environment (KEY=VALUE per line)", "API_KEY=...");
  form.addEventListener("submit", (event) => {
    event.preventDefault();
    error.hidden = true;
    const serverName = name.value.trim();
    const commandText = command.value.trim();
    const urlText = url.value.trim();
    const parsedArgs = parseArgsText(args.value);
    const parsedEnv = parseEnvText(env.value);
    let rejected = "";
    if (serverName === "") rejected = "A server name is required.";
    else if (commandText !== "" && urlText !== "") rejected = "Choose either a command or a URL, not both.";
    else if (commandText === "" && urlText === "") rejected = "A command or a URL is required.";
    else if (parsedEnv.rejected.length > 0) {
      rejected = `These environment lines are not KEY=VALUE:
${parsedEnv.rejected.join("\n")}`;
    }
    if (rejected !== "") {
      error.textContent = rejected;
      error.hidden = false;
      return;
    }
    const entry = urlText !== "" ? { url: urlText } : {
      command: commandText,
      ...parsedArgs.length > 0 ? { args: parsedArgs } : {},
      ...Object.keys(parsedEnv.env).length > 0 ? { env: parsedEnv.env } : {}
    };
    send({ action: "add", name: serverName, entry });
  });
  const submit = el("button", void 0, "Add server");
  submit.type = "submit";
  form.append(submit, error);
  section.append(form);
  return section;
}
function layersSection(state) {
  const section = el("section");
  section.append(el("h4", void 0, "Config layers (lowest precedence first)"));
  const list = el("ul");
  for (const layer of state.layers) {
    const item = el("li", layer.exists ? void 0 : "muted");
    const detail = layer.exists ? `${layer.serverCount} server(s)` : "not present";
    item.append(el("span", void 0, `${layer.label} - ${layer.path} - ${detail}`));
    if (layer.writable) item.append(" ", el("span", "muted", "(written by this plugin)"));
    if (layer.error) item.append(" ", el("span", "error", layer.error.message));
    list.append(item);
  }
  section.append(list);
  return section;
}
var client_default = {
  mount(container, ctx) {
    const root = el("div", "mcp-manager");
    const style = el("style");
    style.textContent = STYLES;
    const error = el("div", "error");
    error.hidden = true;
    const body = el("div");
    root.append(style, error, body);
    container.append(root);
    const send = (payload) => ctx.send(payload);
    function render(state) {
      error.hidden = true;
      const header = el("div");
      const title = el("h3", void 0, "MCP servers");
      const hint = el("p", "hint");
      hint.append(
        "Read from the pi-mcp-adapter config layers; changes are written to ",
        el("code", void 0, state.projectOverridePath),
        " only. Run ",
        el("code", void 0, "/reload"),
        " in pi to apply them."
      );
      const actions = el("div");
      actions.append(button("Refresh", () => send({ action: "list" })));
      header.append(title, hint, actions);
      body.replaceChildren(header, serversSection(state, send), addSection(send), layersSection(state));
    }
    function showError(message) {
      error.textContent = message;
      error.hidden = false;
    }
    const off = ctx.onData((payload) => {
      const message = payload;
      if (message?.type === "state") render(message.state);
      else if (message?.type === "error") showError(`${message.action} failed: ${message.message}`);
    });
    send({ action: "list" });
    return () => {
      off();
      root.remove();
    };
  }
};
export {
  client_default as default,
  parseArgsText,
  parseEnvText,
  summarizeEntry
};
