/* Generated by scripts/build-plugins.mjs from plugins/worktree-preparer/src/index.ts - do not edit. */

// plugins/worktree-preparer/src/ops.ts
import { cp, mkdir as makeDirectory } from "node:fs/promises";
import { execFile } from "node:child_process";
import { basename, dirname, isAbsolute, relative, resolve, sep } from "node:path";
import { promisify } from "node:util";
var DEFAULT_EXCLUDES = [".git", "node_modules", "dist", "build", "coverage"];
var execFileAsync = promisify(execFile);
var defaultRunner = {
  async run(command, args, cwd) {
    try {
      const result = await execFileAsync(command, args, { cwd, maxBuffer: 1024 * 1024 });
      return { code: 0, stdout: result.stdout, stderr: result.stderr };
    } catch (error) {
      const failure = error;
      return {
        code: typeof failure.code === "number" ? failure.code : 1,
        stdout: failure.stdout ?? "",
        stderr: failure.stderr ?? failure.message ?? String(error)
      };
    }
  }
};
var defaultFileOperations = {
  async mkdir(path, recursive = false) {
    await makeDirectory(path, { recursive });
  },
  async copyTree(source, destination, excludes) {
    const excluded = new Set(excludes);
    await cp(source, destination, {
      recursive: true,
      filter: (entry) => !excluded.has(basename(entry))
    });
  }
};
function inside(root, candidate) {
  const suffix = relative(root, candidate);
  return suffix === "" || suffix !== ".." && !suffix.startsWith(`..${sep}`) && !isAbsolute(suffix);
}
function workspacePath(workspaceRoot, value, label) {
  if (typeof workspaceRoot !== "string" || !isAbsolute(workspaceRoot))
    return `${label} must use an absolute workspace path`;
  if (typeof value !== "string" || value.trim() === "") return `${label} must not be empty`;
  if (isAbsolute(value) || /^[A-Za-z]:[\\/]/.test(value)) return `${label} must stay inside the workspace`;
  const normalized = value.replaceAll("\\", sep);
  if (normalized.split(sep).includes("..")) return `${label} escapes the workspace`;
  const candidate = resolve(workspaceRoot, normalized);
  return inside(resolve(workspaceRoot), candidate) ? null : `${label} escapes the workspace`;
}
function validateSelection(workspaceRoot, selection) {
  return workspacePath(workspaceRoot, selection, `selection "${String(selection)}"`);
}
function validateBranchName(branch) {
  if (typeof branch !== "string" || branch.length === 0) return "branch name must not be empty";
  if (branch.startsWith("-") || branch.startsWith("/") || branch.endsWith("/") || branch.endsWith(".") || branch === "@" || branch.includes("..") || branch.includes("//") || branch.includes("@{") || branch.split("/").some((part) => part === "" || part.startsWith(".") || part.endsWith(".") || part.endsWith(".lock")) || /[\x00-\x20\x7f~^:?*[\\]/.test(branch)) {
    return `invalid branch name "${branch}"`;
  }
  return null;
}
function errorText(source, action, result) {
  const detail = (result.stderr || result.stdout).trim();
  return `${source}: ${action}${detail ? ` (${detail})` : " failed"}`;
}
function isNotRepository(result) {
  return /not a git repository|not a git repo|no git repository/i.test(result.stderr);
}
async function prepareProject(input, deps = {}) {
  const workspaceRoot = resolve(input.workspaceRoot);
  const branchError = validateBranchName(input.branch);
  if (branchError) throw new Error(branchError);
  if (!isAbsolute(input.workspaceRoot)) throw new Error("workspaceRoot must use an absolute path");
  const outputError = workspacePath(workspaceRoot, input.outputName, "output");
  if (outputError) throw new Error(outputError);
  if (!Array.isArray(input.selections)) throw new Error("selections must be an array");
  const outputRoot = resolve(workspaceRoot, input.outputName.replaceAll("\\", sep));
  const selectedPaths = [];
  for (const selection of input.selections) {
    const selectionError = validateSelection(workspaceRoot, selection);
    if (selectionError) throw new Error(selectionError);
    const selected = resolve(workspaceRoot, selection.replaceAll("\\", sep));
    if (inside(selected, outputRoot) || inside(outputRoot, selected)) {
      throw new Error(`selection "${selection}" conflicts with output path`);
    }
    if (!selectedPaths.includes(selected)) selectedPaths.push(selected);
  }
  const runner = deps.runner ?? defaultRunner;
  const fs = deps.fs ?? defaultFileOperations;
  await fs.mkdir(dirname(outputRoot), true);
  await fs.mkdir(outputRoot);
  const result = { root: outputRoot, branch: input.branch, entries: [], errors: [] };
  const handledRoots = /* @__PURE__ */ new Set();
  const handledSelections = [];
  const destinationNames = /* @__PURE__ */ new Set();
  for (const selected of selectedPaths) {
    if (handledSelections.some((parent) => inside(parent, selected))) continue;
    let probe;
    try {
      probe = await runner.run("git", ["-C", selected, "rev-parse", "--show-toplevel"], workspaceRoot);
    } catch (error) {
      probe = { code: 1, stdout: "", stderr: String(error) };
    }
    if (probe.code === 0) {
      const rootText = probe.stdout.trim();
      if (!rootText) {
        result.errors.push(`${selected}: Git discovery returned no repository root`);
        handledSelections.push(selected);
        continue;
      }
      const repository = resolve(rootText);
      if (!inside(workspaceRoot, repository)) {
        result.errors.push(`${selected}: git repository is outside the workspace`);
        handledSelections.push(selected);
        continue;
      }
      if (handledRoots.has(repository)) {
        handledSelections.push(selected);
        continue;
      }
      handledRoots.add(repository);
      handledSelections.push(selected);
      const name2 = basename(selected);
      if (destinationNames.has(name2)) {
        result.errors.push(`${selected}: duplicate destination name "${name2}"`);
        continue;
      }
      destinationNames.add(name2);
      const destination2 = resolve(outputRoot, name2);
      try {
        const fetched = await runner.run("git", ["-C", repository, "fetch", "origin", "master"], repository);
        if (fetched.code !== 0) {
          result.errors.push(errorText(repository, "fetch origin/master", fetched));
          continue;
        }
        const added = await runner.run(
          "git",
          ["-C", repository, "worktree", "add", "-b", input.branch, destination2, "origin/master"],
          repository
        );
        if (added.code !== 0) {
          result.errors.push(errorText(repository, "create worktree", added));
          continue;
        }
        result.entries.push({ source: repository, destination: destination2, kind: "worktree" });
      } catch (error) {
        result.errors.push(`${repository}: ${String(error)}`);
      }
      continue;
    }
    if (!isNotRepository(probe)) {
      result.errors.push(errorText(selected, "inspect Git repository", probe));
      handledSelections.push(selected);
      continue;
    }
    const name = basename(selected);
    if (destinationNames.has(name)) {
      result.errors.push(`${selected}: duplicate destination name "${name}"`);
      handledSelections.push(selected);
      continue;
    }
    destinationNames.add(name);
    const destination = resolve(outputRoot, name);
    try {
      await fs.copyTree(selected, destination, DEFAULT_EXCLUDES);
      result.entries.push({ source: selected, destination, kind: "copy" });
    } catch (error) {
      result.errors.push(`${selected}: copy failed (${String(error)})`);
    }
    handledSelections.push(selected);
  }
  return result;
}

// plugins/worktree-preparer/src/index.ts
function isRecord(value) {
  return Boolean(value && typeof value === "object");
}
var index_default = {
  activate(host) {
    let state = { kind: "state", cwd: host.cwd, folders: [], result: null, error: null };
    const publish = (clientId) => {
      host.broadcast(state);
      if (clientId) host.sendTo(clientId, state);
    };
    const refresh = async (clientId) => {
      try {
        const entries = await host.fs.list();
        state = {
          ...state,
          cwd: host.cwd,
          folders: entries.filter((entry) => entry.type === "dir").map((entry) => entry.name).sort(),
          error: null
        };
      } catch (error) {
        state = { ...state, cwd: host.cwd, error: String(error) };
      }
      publish(clientId);
    };
    const unregister = host.onMessage(async (payload, from) => {
      if (!isRecord(payload) || typeof payload.action !== "string") return;
      if (payload.action === "get_state") {
        await refresh(from);
        return;
      }
      if (payload.action !== "prepare") return;
      try {
        const selections = Array.isArray(payload.selections) ? payload.selections.filter((selection) => typeof selection === "string") : [];
        const result = await prepareProject({
          workspaceRoot: host.cwd,
          outputName: typeof payload.outputName === "string" ? payload.outputName : "",
          branch: typeof payload.branch === "string" ? payload.branch : "",
          selections
        });
        state = { ...state, cwd: host.cwd, result, error: result.errors.length ? result.errors.join("; ") : null };
      } catch (error) {
        state = { ...state, cwd: host.cwd, result: null, error: String(error) };
      }
      publish(from);
      if (!from) publish();
    });
    const onAttach = host.onAttach?.((clientId) => void refresh(clientId));
    const onCwdChange = host.onCwdChange?.(() => void refresh());
    return () => {
      unregister();
      onAttach?.();
      onCwdChange?.();
    };
  }
};
export {
  index_default as default
};
