/* Generated by scripts/build-plugins.mjs from plugins/mcp-manager/src/index.ts - do not edit. */

// plugins/mcp-manager/src/index.ts
import { homedir } from "node:os";
import { join as join2 } from "node:path";

// plugins/mcp-manager/src/config.ts
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
var REDACTED = "***";
var UNSAFE_NAMES = /* @__PURE__ */ new Set(["__proto__", "constructor", "prototype"]);
var STDIO_FIELDS = ["command", "args", "env", "cwd", "inheritEnv", "literalEnv", "pluginDataDir"];
var HTTP_FIELDS = [
  "url",
  "headers",
  "caFile",
  "auth",
  "bearerToken",
  "bearerTokenEnv",
  "bearerTokenStore",
  "requestHeadersCommand",
  "httpTransport"
];
var URL_BOUND_FIELDS = [
  "headers",
  "caFile",
  "bearerToken",
  "bearerTokenEnv",
  "bearerTokenStore",
  "requestHeadersCommand"
];
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function messageOf(err) {
  return isRecord(err) && typeof err.message === "string" ? err.message : String(err);
}
function codeOf(err, fallback) {
  return isRecord(err) && typeof err.code === "string" ? err.code : fallback;
}
function fail(path, code, message) {
  return { ok: false, path, code, message };
}
function configLayers(roots) {
  return [
    {
      id: "shared-global",
      label: "user-global standard MCP",
      path: join(roots.home, ".config", "mcp", "mcp.json"),
      scope: "global",
      piOwned: false,
      writable: false
    },
    {
      id: "agents-global",
      label: "user-global .agents MCP",
      path: join(roots.home, ".agents", "mcp.json"),
      scope: "global",
      piOwned: false,
      writable: false
    },
    {
      id: "agents-nested-global",
      label: "user-global .agents nested MCP",
      path: join(roots.home, ".agents", "mcp", "mcp.json"),
      scope: "global",
      piOwned: false,
      writable: false
    },
    {
      id: "pi-global",
      label: "Pi global override",
      path: join(roots.agentDir, "mcp.json"),
      scope: "global",
      piOwned: true,
      writable: false
    },
    {
      id: "shared-project",
      label: "project standard MCP",
      path: join(roots.projectDir, ".mcp.json"),
      scope: "project",
      piOwned: false,
      writable: false
    },
    {
      id: "pi-project",
      label: "project Pi override",
      path: join(roots.projectDir, ".pi", "mcp.json"),
      scope: "project",
      piOwned: true,
      writable: true
    }
  ];
}
function projectOverridePath(roots) {
  return join(roots.projectDir, ".pi", "mcp.json");
}
function serversOf(parsed) {
  if (!isRecord(parsed)) return {};
  const raw = parsed.mcpServers ?? parsed["mcp-servers"];
  if (!isRecord(raw)) return {};
  return Object.fromEntries(Object.entries(raw).filter(([, entry]) => isRecord(entry)));
}
function readLayer(layer) {
  if (!existsSync(layer.path)) return { layer, exists: false, servers: {} };
  let text;
  try {
    text = readFileSync(layer.path, "utf8");
  } catch (err) {
    return {
      layer,
      exists: true,
      servers: {},
      error: { code: codeOf(err, "read-failed"), message: `cannot read ${layer.path}: ${messageOf(err)}` }
    };
  }
  try {
    return { layer, exists: true, servers: serversOf(JSON.parse(text)) };
  } catch (err) {
    return {
      layer,
      exists: true,
      servers: {},
      error: { code: "invalid-json", message: `invalid JSON in ${layer.path}: ${messageOf(err)}` }
    };
  }
}
function readLayers(roots) {
  return configLayers(roots).map(readLayer);
}
function mergeEntry(base, next) {
  const merged = { ...base };
  const toHttp = typeof next.url === "string" && typeof merged.command === "string";
  const toStdio = typeof next.command === "string" && typeof merged.url === "string";
  const dropped = toHttp ? STDIO_FIELDS : toStdio ? HTTP_FIELDS : [];
  for (const field of dropped) delete merged[field];
  if (typeof next.url === "string" && typeof merged.url === "string" && next.url !== merged.url) {
    for (const field of URL_BOUND_FIELDS) delete merged[field];
  }
  return { ...merged, ...next };
}
function resolveServers(states) {
  const merged = /* @__PURE__ */ new Map();
  for (const state of states) {
    for (const [name, entry] of Object.entries(state.servers)) {
      const previous = merged.get(name);
      merged.set(
        name,
        previous ? {
          entry: mergeEntry(previous.entry, entry),
          source: state.layer,
          layers: [...previous.layers, state.layer.id]
        } : { entry: { ...entry }, source: state.layer, layers: [state.layer.id] }
      );
    }
  }
  return [...merged].map(([name, value]) => ({
    name,
    entry: value.entry,
    source: value.source,
    layers: value.layers,
    disabled: value.entry.disabled === true
  })).sort((left, right) => left.name.localeCompare(right.name));
}
function readProjectDoc(path) {
  if (!existsSync(path)) {
    return { ok: true, doc: { existed: false, raw: {}, serverKey: "mcpServers", servers: {} } };
  }
  let parsed;
  try {
    parsed = JSON.parse(readFileSync(path, "utf8"));
  } catch (err) {
    const reason = codeOf(err, "") === "" ? `invalid JSON (${messageOf(err)})` : messageOf(err);
    return { ok: false, result: fail(path, "read-failed", `cannot use ${path}: ${reason}`) };
  }
  if (!isRecord(parsed)) {
    return { ok: false, result: fail(path, "invalid-config", `${path} must contain a JSON object`) };
  }
  const serverKey = parsed.mcpServers === void 0 && parsed["mcp-servers"] !== void 0 ? "mcp-servers" : "mcpServers";
  const existing = parsed[serverKey];
  if (existing !== void 0 && !isRecord(existing)) {
    return { ok: false, result: fail(path, "invalid-config", `${serverKey} in ${path} must be an object`) };
  }
  return {
    ok: true,
    doc: {
      existed: true,
      raw: parsed,
      serverKey,
      servers: { ...existing }
    }
  };
}
function writeProjectDoc(path, raw) {
  const tmp = `${path}.${process.pid}.tmp`;
  try {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(tmp, `${JSON.stringify(raw, null, 2)}
`, "utf8");
    renameSync(tmp, path);
    return { ok: true, path, changed: true };
  } catch (err) {
    return fail(path, "write-failed", `cannot write ${path}: ${messageOf(err)}`);
  }
}
function mutateProjectConfig(roots, mutate) {
  const path = projectOverridePath(roots);
  const read = readProjectDoc(path);
  if (!read.ok) return read.result;
  const { doc } = read;
  const before = JSON.stringify(doc.raw);
  const failure = mutate(doc.servers);
  if (failure) return failure;
  if (!doc.existed && Object.keys(doc.servers).length === 0) return { ok: true, path, changed: false };
  doc.raw[doc.serverKey] = doc.servers;
  if (JSON.stringify(doc.raw) === before) return { ok: true, path, changed: false };
  return writeProjectDoc(path, doc.raw);
}
function validName(name) {
  return typeof name === "string" && name.trim() !== "" && !UNSAFE_NAMES.has(name);
}
function invalidName(path, name) {
  return fail(path, "invalid-name", `"${typeof name === "string" ? name : String(name)}" is not a usable server name`);
}
function setServerDisabled(roots, name, disabled) {
  const path = projectOverridePath(roots);
  if (!validName(name)) return invalidName(path, name);
  const lowerDisabled = disabled || resolveServers(readLayers(roots).filter((state) => state.layer.id !== "pi-project")).find(
    (server) => server.name === name
  )?.disabled === true;
  return mutateProjectConfig(roots, (servers) => {
    const previous = servers[name];
    if (previous !== void 0 && !isRecord(previous)) {
      return fail(path, "invalid-config", `server "${name}" in ${path} must be an object`);
    }
    const existing = previous;
    let next;
    if (disabled) {
      next = { ...existing, disabled: true };
    } else {
      next = Object.fromEntries(Object.entries(existing ?? {}).filter(([key]) => key !== "disabled"));
      if (lowerDisabled) next.disabled = false;
    }
    if (Object.keys(next).length === 0) delete servers[name];
    else servers[name] = next;
    return void 0;
  });
}
function addServer(roots, name, entry) {
  const path = projectOverridePath(roots);
  if (!validName(name)) return invalidName(path, name);
  const hasCommand = typeof entry.command === "string" && entry.command.trim() !== "";
  const hasUrl = typeof entry.url === "string" && entry.url.trim() !== "";
  if (!hasCommand && !hasUrl) {
    return fail(path, "invalid-entry", `server "${name}" needs a non-empty command or url`);
  }
  return mutateProjectConfig(roots, (servers) => {
    servers[name] = { ...entry };
    return void 0;
  });
}
function removeServer(roots, name) {
  const path = projectOverridePath(roots);
  if (!validName(name)) return invalidName(path, name);
  return mutateProjectConfig(roots, (servers) => {
    delete servers[name];
    return void 0;
  });
}
function maskValues(record) {
  return Object.fromEntries(Object.keys(record).map((key) => [key, REDACTED]));
}
function redactEntry(entry) {
  const redacted = { ...entry };
  if (isRecord(redacted.env)) redacted.env = maskValues(redacted.env);
  if (isRecord(redacted.headers)) redacted.headers = maskValues(redacted.headers);
  if (typeof redacted.bearerToken === "string") redacted.bearerToken = REDACTED;
  const oauth = redacted.oauth;
  if (isRecord(oauth) && typeof oauth.clientSecret === "string") {
    redacted.oauth = { ...oauth, clientSecret: REDACTED };
  }
  return redacted;
}
function toClientState(roots) {
  const states = readLayers(roots);
  return {
    layers: states.map((state) => ({
      ...state.layer,
      exists: state.exists,
      serverCount: Object.keys(state.servers).length,
      ...state.error ? { error: state.error } : {}
    })),
    servers: resolveServers(states).map((server) => ({ ...server, entry: redactEntry(server.entry) })),
    projectOverridePath: projectOverridePath(roots)
  };
}

// plugins/mcp-manager/src/index.ts
function agentDir() {
  const configured = process.env.PI_CODING_AGENT_DIR?.trim();
  if (!configured) return join2(homedir(), ".pi", "agent");
  return configured.startsWith("~/") ? join2(homedir(), configured.slice(2)) : configured;
}
function defaultRoots(host) {
  return { home: homedir(), agentDir: agentDir(), projectDir: host.cwd };
}
function isRecord2(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function asName(value) {
  return typeof value === "string" ? value : "";
}
function asEntry(value) {
  return isRecord2(value) ? value : void 0;
}
function errorMessage(action, code, message) {
  return { type: "error", action, code, message };
}
function reply(action, result, roots) {
  if (result.ok) return { type: "state", state: toClientState(roots) };
  return errorMessage(action, result.code, result.message);
}
function handle(payload, roots) {
  const message = isRecord2(payload) ? payload : {};
  const action = typeof message.action === "string" ? message.action : "";
  switch (action) {
    case "list":
      return { type: "state", state: toClientState(roots) };
    case "toggle":
      return reply(action, setServerDisabled(roots, asName(message.name), message.disabled !== false), roots);
    case "add": {
      const entry = asEntry(message.entry);
      if (!entry) {
        return errorMessage(action, "invalid-entry", "a server definition object is required");
      }
      return reply(action, addServer(roots, asName(message.name), entry), roots);
    }
    case "remove":
      return reply(action, removeServer(roots, asName(message.name)), roots);
    default:
      return errorMessage(action, "unknown-action", action === "" ? "missing action" : `unknown action "${action}"`);
  }
}
function createEntry(resolveRoots = defaultRoots) {
  return {
    activate(host) {
      return host.onMessage((payload, from) => {
        const response = handle(payload, resolveRoots(host));
        if (from) host.sendTo(from, response);
        else host.broadcast(response);
      });
    }
  };
}
var index_default = createEntry();
export {
  createEntry,
  index_default as default,
  defaultRoots
};
