/* Generated by scripts/build-plugins.mjs from plugins/ui-shortcuts/src/client.ts - do not edit. */

// plugins/ui-shortcuts/src/client.ts
var SHORTCUTS = [
  { key: "t", label: "Terminal", view: "terminal" },
  { key: "e", label: "Editor", view: "plugin:vscode-editor" },
  { key: "r", label: "Run Trace", view: "plugin:run-trace" }
];
function shortcutForEvent(event) {
  if (!event || event.defaultPrevented || event.repeat || event.isComposing || !(event.ctrlKey || event.metaKey) || !event.altKey || event.shiftKey)
    return void 0;
  const key = typeof event.key === "string" ? event.key.toLowerCase() : "";
  return SHORTCUTS.find((shortcut) => shortcut.key === key);
}
function isEditableTarget(target) {
  if (!target || typeof target !== "object") return false;
  const element = target;
  const tagName = typeof element.tagName === "string" ? element.tagName.toUpperCase() : "";
  return element.isContentEditable === true || tagName === "INPUT" || tagName === "TEXTAREA" || tagName === "SELECT";
}
function keyLabel(shortcut) {
  return `Ctrl+Alt+${shortcut.key.toUpperCase()}`;
}
var client_default = {
  mount(container, _ctx) {
    if (!container || typeof container.append !== "function") return () => {
    };
    const hostWindow = container.ownerDocument?.defaultView;
    if (!hostWindow) return () => {
    };
    let activeView = null;
    const setView = (view) => {
      const bridge = hostWindow.__piWebUiHost;
      if (!bridge || typeof bridge.setView !== "function") return false;
      try {
        bridge.setView(view);
        return true;
      } catch {
        return false;
      }
    };
    const toggleView = (view) => {
      const next = activeView === view ? "chat" : view;
      if (setView(next)) activeView = next === "chat" ? null : view;
    };
    const buttons = SHORTCUTS.map((shortcut) => {
      const button = container.ownerDocument.createElement("button");
      button.type = "button";
      button.textContent = shortcut.label;
      button.dataset.view = shortcut.view;
      button.dataset.key = keyLabel(shortcut);
      button.setAttribute("aria-keyshortcuts", keyLabel(shortcut));
      button.addEventListener("click", () => toggleView(shortcut.view));
      return button;
    });
    container.append(...buttons);
    const onKey = (event) => {
      if (isEditableTarget(event.target)) return;
      const shortcut = shortcutForEvent(event);
      if (!shortcut) return;
      event.preventDefault();
      toggleView(shortcut.view);
    };
    hostWindow.addEventListener("keydown", onKey);
    return () => {
      hostWindow.removeEventListener("keydown", onKey);
      container.replaceChildren();
    };
  }
};
export {
  SHORTCUTS,
  client_default as default,
  shortcutForEvent
};
