#!/usr/bin/env node
/**
 * Convention-driven plugin builder for the whole repo.
 *
 * pi-web-ui hardcodes the artifact filenames it loads, so every plugin is
 * authored in TypeScript and compiled to exactly those paths:
 *
 *   plugins/<id>/src/index.ts   ->  plugins/<id>/index.mjs
 *   plugins/<id>/src/client.ts  ->  plugins/<id>/client/entry.mjs
 *
 * The server bundle keeps npm specifiers external (platform node): a plugin
 * resolves its runtime dependencies through createRequire plus the host's
 * ensureDeps auto-install, exactly like upstream does. The plugin's own
 * relative src/*.ts imports are inlined, so index.mjs is a single file.
 *
 * The client bundle inlines everything (platform browser): the host serves only
 * the client/ subtree over HTTP and the browser loads entry.mjs as bare ESM, so
 * no bare npm specifier may survive in it. `.css` imports become strings
 * (vscode-editor inlines the xterm stylesheet that way).
 *
 * A plugin directory without src/ is skipped with a note rather than treated as
 * an error, because plugins are converted to TypeScript one at a time.
 *
 * Usage:
 *   node scripts/build-plugins.mjs           # every plugin + the vendor bundles
 *   node scripts/build-plugins.mjs <id>      # one plugin + only its vendor bundle
 */
import { build } from "esbuild";
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PLUGINS_DIR = join(ROOT, "plugins");

/** Vendor bundles that belong to a specific plugin id, built after that plugin. */
const VENDOR_BUILDS = [
	{ pluginId: "mermaid", script: "build-mermaid-vendor.mjs" },
	{ pluginId: "run-trace", script: "build-runtrace-vendor.mjs" },
];

/** Plugin directory names, sorted, ignoring anything that is not a directory. */
function pluginIds() {
	if (!existsSync(PLUGINS_DIR)) return [];
	return readdirSync(PLUGINS_DIR)
		.filter((name) => statSync(join(PLUGINS_DIR, name)).isDirectory())
		.sort();
}

function bannerFor(sourceFile) {
	return `/* Generated by scripts/build-plugins.mjs from ${sourceFile} - do not edit. */`;
}

/** Build plugins/<id>/index.mjs from plugins/<id>/src/index.ts. */
async function buildServerEntry(id) {
	const entry = join(PLUGINS_DIR, id, "src", "index.ts");
	const outfile = join(PLUGINS_DIR, id, "index.mjs");
	await build({
		entryPoints: [entry],
		outfile,
		bundle: true,
		platform: "node",
		format: "esm",
		target: "es2022",
		// Node builtins and npm specifiers stay external: the host auto-installs
		// runtime drivers and the plugin resolves them with createRequire.
		packages: "external",
		charset: "utf8",
		banner: { js: bannerFor(`plugins/${id}/src/index.ts`) },
	});
	return outfile;
}

/** Build plugins/<id>/client/entry.mjs from plugins/<id>/src/client.ts. */
async function buildClientEntry(id) {
	const entry = join(PLUGINS_DIR, id, "src", "client.ts");
	const outfile = join(PLUGINS_DIR, id, "client", "entry.mjs");
	await build({
		entryPoints: [entry],
		outfile,
		bundle: true,
		platform: "browser",
		format: "esm",
		target: "es2022",
		// import "@xterm/xterm/css/xterm.css" becomes an inlined string.
		loader: { ".css": "text" },
		// Vendor bundles are loaded at runtime by URL from the client/ subtree the
		// host serves, so esbuild must not try to inline or resolve them.
		external: ["./vendor/*"],
		charset: "utf8",
		banner: { js: bannerFor(`plugins/${id}/src/client.ts`) },
	});
	return outfile;
}

/** Run a vendor build script in its own process; throws on non-zero exit. */
function runVendorBuild(script) {
	execFileSync(process.execPath, [join(ROOT, "scripts", script)], {
		cwd: ROOT,
		stdio: "inherit",
	});
}

async function main() {
	const requested = process.argv[2];
	const ids = pluginIds();

	if (requested !== undefined) {
		if (!ids.includes(requested)) {
			console.error(`Unknown plugin id "${requested}". Known ids: ${ids.join(", ") || "(none)"}`);
			process.exit(1);
		}
	}

	const scope = requested === undefined ? ids : [requested];
	const built = [];
	const skipped = [];
	const failed = [];

	for (const id of scope) {
		const srcDir = join(PLUGINS_DIR, id, "src");
		const hasServer = existsSync(join(srcDir, "index.ts"));
		const hasClient = existsSync(join(srcDir, "client.ts"));

		if (!existsSync(srcDir) || (!hasServer && !hasClient)) {
			skipped.push(id);
			console.log(`- ${id}: no src/index.ts or src/client.ts yet, skipped`);
			continue;
		}

		const artifacts = [];
		try {
			if (hasServer) artifacts.push(await buildServerEntry(id));
			if (hasClient) artifacts.push(await buildClientEntry(id));
		} catch (err) {
			// esbuild already printed its diagnostics to stderr; keep the reason short.
			failed.push(id);
			console.error(`x ${id}: build failed (${err instanceof Error ? err.message : String(err)})`);
			continue;
		}

		built.push(id);
		for (const artifact of artifacts) {
			const bytes = statSync(artifact).size;
			console.log(`+ ${id}: ${artifact.slice(ROOT.length + 1)} (${bytes} bytes)`);
		}

		// A single-plugin build only refreshes the vendor bundle it owns.
		for (const vendor of VENDOR_BUILDS) {
			if (vendor.pluginId !== id) continue;
			try {
				runVendorBuild(vendor.script);
			} catch {
				failed.push(`${id} vendor`);
				console.error(`x ${id}: vendor build ${vendor.script} failed`);
			}
		}
	}

	if (requested === undefined) {
		for (const vendor of VENDOR_BUILDS) {
			// Already handled above when its plugin was in scope and built.
			if (built.includes(vendor.pluginId)) continue;
			try {
				runVendorBuild(vendor.script);
			} catch {
				failed.push(`${vendor.pluginId} vendor`);
				console.error(`x ${vendor.pluginId}: vendor build ${vendor.script} failed`);
			}
		}
	}

	console.log(
		`\nSummary: ${built.length} built${built.length ? ` (${built.join(", ")})` : ""}, ` +
			`${skipped.length} skipped${skipped.length ? ` (${skipped.join(", ")})` : ""}, ` +
			`${failed.length} failed${failed.length ? ` (${failed.join(", ")})` : ""}`,
	);

	if (failed.length > 0) process.exit(1);
}

await main();
