/* Generated by scripts/build-plugins.mjs from plugins/webmail/src/index.ts - do not edit. */

// plugins/webmail/src/index.ts
import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { createRequire } from "node:module";

// plugins/webmail/src/protocol.ts
var STATUS_UNCONFIGURED = "Not configured";
var STATUS_CONNECTED = "Connected";
var STATUS_FAILED_PREFIX = "Connection failed";
function failedStatus(reason) {
  return `${STATUS_FAILED_PREFIX}: ${reason}`;
}

// plugins/webmail/src/index.ts
var CONFIG_FILE = "config.json";
var BODY_LIMIT = 16e3;
var SEARCH_SCAN = 1e3;
var DEP_NAMES = ["imapflow", "mailparser", "nodemailer"];
var DEFAULT_CONFIG = {
  imap: { host: "", port: 993, tls: true, user: "", pass: "" },
  smtp: {
    host: "",
    port: 465,
    tls: true,
    user: "",
    pass: "",
    from: ""
  },
  pollSec: 60,
  notifyEnabled: true,
  aiEnabled: false
};
async function loadConfig(dir) {
  const raw = join(dir, CONFIG_FILE);
  if (!existsSync(raw)) return structuredClone(DEFAULT_CONFIG);
  try {
    const parsed = JSON.parse(await readFile(raw, "utf8"));
    return {
      ...structuredClone(DEFAULT_CONFIG),
      ...parsed,
      imap: { ...DEFAULT_CONFIG.imap, ...parsed.imap },
      smtp: { ...DEFAULT_CONFIG.smtp, ...parsed.smtp }
    };
  } catch {
    return structuredClone(DEFAULT_CONFIG);
  }
}
async function saveConfig(dir, cfg) {
  await writeFile(join(dir, CONFIG_FILE), JSON.stringify(cfg, null, "	"), "utf8");
}
function resolveNpmCli() {
  try {
    return createRequire(import.meta.url).resolve("npm/bin/npm-cli.js");
  } catch {
    return null;
  }
}
function reasonText(err) {
  const message = err?.message;
  return message === void 0 || message === null ? String(err) : String(message);
}
function envFrom(envelope) {
  const addr = envelope?.from?.[0];
  return addr ? addr.address ?? "" : "";
}
function envName(envelope) {
  const addr = envelope?.from?.[0];
  return addr?.name || "";
}
function summarize(msg) {
  return {
    uid: msg.uid,
    from: envFrom(msg.envelope),
    fromName: envName(msg.envelope),
    to: (msg.envelope?.to ?? []).map((a) => a.address ?? "").join(", "),
    subject: msg.envelope?.subject || "(no subject)",
    date: msg.envelope?.date ? new Date(msg.envelope.date).toISOString() : "",
    seen: Boolean(msg.flags?.has("\\Seen")),
    size: msg.size ?? 0
  };
}
var index_default = {
  activate(host) {
    const st = {
      config: null,
      client: null,
      chain: Promise.resolve(),
      pollTimer: null,
      pollBusy: false,
      lastUnseenUids: /* @__PURE__ */ new Set(),
      firstPollDone: false,
      deps: { imapflow: null, mailparser: null, nodemailer: null },
      depsOk: false,
      depsInstalling: false,
      status: STATUS_UNCONFIGURED,
      lastCheckAt: 0,
      unseenTotal: 0,
      toolUnregister: null,
      bgTask: null,
      installChild: null
    };
    const sec = host.secrets;
    let secretsDegradedWarned = false;
    function storeSecret(name, value) {
      if (!sec?.set || !value) return false;
      try {
        sec.set(name, String(value));
        return sec.get?.(name) === String(value);
      } catch (err) {
        host.log(`failed to write secret ${name}:`, reasonText(err));
        return false;
      }
    }
    function warnSecretsDegraded() {
      if (secretsDegradedWarned) return;
      secretsDegradedWarned = true;
      host.log("encrypted storage unavailable; the password was saved as plain text in config.json");
      host.notify(
        "warning",
        "📬 Webmail: encrypted storage unavailable - the password was saved as plain text in config.json (functionality unaffected)"
      );
    }
    async function loadConfigSecure() {
      const cfg = await loadConfig(host.dir);
      if (sec?.set) {
        let migrated = false;
        for (const [sect, secretName] of [
          ["imap", "imap_pass"],
          ["smtp", "smtp_pass"]
        ]) {
          const legacy = cfg[sect].pass;
          if (!legacy) continue;
          if (storeSecret(secretName, legacy)) {
            cfg[sect].pass = "";
            migrated = true;
          } else {
            warnSecretsDegraded();
          }
        }
        if (migrated) {
          try {
            await saveConfig(host.dir, cfg);
          } catch {
          }
          host.log("migrated plaintext passwords to encrypted storage");
        }
      }
      return rehydrate(cfg);
    }
    function rehydrate(cfg) {
      if (!sec?.get || !cfg) return cfg;
      const ip = sec.get("imap_pass");
      const sp = sec.get("smtp_pass");
      if (ip !== void 0 && !cfg.imap.pass) cfg.imap.pass = ip;
      if (sp !== void 0 && !cfg.smtp.pass) cfg.smtp.pass = sp;
      return cfg;
    }
    function publicState() {
      const c = st.config;
      return {
        configured: Boolean(c?.imap?.host && c?.imap?.user),
        depsOk: st.depsOk,
        depsInstalling: st.depsInstalling,
        status: st.status,
        unseen: st.unseenTotal,
        lastCheckAt: st.lastCheckAt,
        aiEnabled: Boolean(c?.aiEnabled),
        notifyEnabled: c?.notifyEnabled !== false && Boolean(c?.imap?.host),
        // Redacted settings echo: passwords are not sent back, only whether
        // one exists.
        config: {
          imap: {
            host: c?.imap?.host ?? "",
            port: c?.imap?.port ?? 993,
            tls: c?.imap?.tls !== false,
            user: c?.imap?.user ?? "",
            hasPass: Boolean(c?.imap?.pass)
          },
          smtp: {
            host: c?.smtp?.host ?? "",
            port: c?.smtp?.port ?? 465,
            tls: c?.smtp?.tls !== false,
            user: c?.smtp?.user ?? "",
            from: c?.smtp?.from ?? "",
            hasPass: Boolean(c?.smtp?.pass)
          },
          pollSec: c?.pollSec ?? 60,
          notifyEnabled: c?.notifyEnabled !== false,
          aiEnabled: Boolean(c?.aiEnabled)
        }
      };
    }
    function broadcastState() {
      host.broadcast({ kind: "state", state: publicState() });
    }
    async function applyConfig(next) {
      next.imap.pass = next.imap.pass || st.config?.imap?.pass || sec?.get?.("imap_pass") || "";
      next.smtp.pass = next.smtp.pass || st.config?.smtp?.pass || sec?.get?.("smtp_pass") || "";
      const onDisk = structuredClone(next);
      let degraded = false;
      for (const [sect, secretName] of [
        ["imap", "imap_pass"],
        ["smtp", "smtp_pass"]
      ]) {
        if (!next[sect].pass) continue;
        if (storeSecret(secretName, next[sect].pass)) onDisk[sect].pass = "";
        else degraded = true;
      }
      if (degraded) warnSecretsDegraded();
      st.config = next;
      await saveConfig(host.dir, onDisk);
      if (!st.depsOk && next.imap?.host) installDeps(true);
      restartPoller();
      await refreshAiTools();
      broadcastState();
    }
    async function loadDeps() {
      const loaded = {};
      for (const name of DEP_NAMES) {
        try {
          loaded[name] = await import(name);
        } catch (err) {
          host.log(`dependency ${name} is not ready:`, reasonText(err));
          loaded[name] = null;
        }
      }
      st.deps = loaded;
      st.depsOk = st.deps.imapflow !== null && st.deps.mailparser !== null;
      if (!st.depsOk || !st.deps.nodemailer) {
        host.log('hint: click "Install dependencies" in the settings panel to finish the installation');
      }
      return st.depsOk;
    }
    function installDeps(auto = false) {
      if (st.depsInstalling) return;
      st.depsInstalling = true;
      host.log(`installing deps: imapflow / mailparser / nodemailer${auto ? " (auto)" : ""}`);
      if (!auto) host.notify("info", "📬 Webmail: installing dependencies…");
      host.notify("info", "📬 Webmail: installing dependencies (imapflow / mailparser / nodemailer)…");
      const pkgs = ["imapflow@latest", "mailparser@latest", "nodemailer@latest"];
      const npmCli = resolveNpmCli();
      const child = npmCli ? spawn(process.execPath, [npmCli, "--prefix", host.dir, "install", ...pkgs, "--no-audit", "--no-fund"], {
        stdio: "ignore"
      }) : spawn(
        process.platform === "win32" ? "npm.cmd" : "npm",
        ["--prefix", host.dir, "install", ...pkgs, "--no-audit", "--no-fund"],
        { stdio: "ignore" }
      );
      st.installChild = child;
      child.on("error", (err) => void finish(false, err.message));
      child.on("exit", (code) => void finish(code === 0, `npm exit ${code}`));
      let done = false;
      async function finish(ok, why) {
        if (done) return;
        done = true;
        st.depsInstalling = false;
        if (st.installChild === child) st.installChild = null;
        if (ok) {
          await loadDeps();
          restartPoller();
          await refreshAiTools();
        }
        host.notify(
          ok ? "success" : "error",
          ok ? "📬 Webmail dependencies installed" : `📬 Webmail dependency installation failed (${why}) - run npm install in the plugin directory by hand, or retry "Install dependencies" in the settings panel`
        );
        broadcastState();
      }
    }
    function serialized(fn) {
      const run = st.chain.then(
        () => fn(),
        () => fn()
      );
      st.chain = run.then(
        () => {
        },
        () => {
        }
      );
      return run;
    }
    function dropClient(why) {
      const c = st.client;
      st.client = null;
      if (c) {
        try {
          c.close();
        } catch {
        }
      }
      if (why) host.log("connection dropped:", why);
    }
    async function ensureClient() {
      const c = st.config?.imap;
      if (!st.deps.imapflow) {
        throw new Error('Dependencies are not installed: click "Install dependencies" in the settings panel');
      }
      if (!c?.host || !c?.user) throw new Error("No IMAP account configured yet");
      if (st.client?.usable) return st.client;
      dropClient();
      const { ImapFlow } = st.deps.imapflow;
      const client = new ImapFlow({
        host: c.host,
        port: Number(c.port) || 993,
        secure: c.tls !== false,
        auth: { user: c.user, pass: c.pass ?? "" },
        logger: false
      });
      client.on("error", (err) => dropClient(err?.message));
      await client.connect();
      st.client = client;
      st.status = STATUS_CONNECTED;
      return client;
    }
    async function withMailbox(folder, fn) {
      const client = await ensureClient();
      const lock = await client.getMailboxLock(folder || "INBOX");
      try {
        return await fn(client);
      } finally {
        lock.release();
      }
    }
    async function listMails(options = {}) {
      const { folder = "INBOX", limit = 30, unseen_only: unseenOnly = false } = options;
      return withMailbox(folder, async (client) => {
        const box = client.mailbox;
        const total = box?.exists ?? 0;
        if (total === 0) return [];
        const start = Math.max(1, total - Math.min(Number(limit) || 30, 200) + 1);
        const out = [];
        const range = `${start}:*`;
        for await (const msg of client.fetch(range, {
          envelope: true,
          flags: true,
          size: true
        })) {
          if (unseenOnly && msg.flags?.has("\\Seen")) continue;
          out.push(summarize(msg));
        }
        out.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
        return out;
      });
    }
    async function searchMails(options = {}) {
      const { query, folder = "INBOX", limit = 20 } = options;
      const q = String(query ?? "").trim().toLowerCase();
      if (!q) return [];
      const pool = await listMails({ folder, limit: SEARCH_SCAN });
      return pool.filter((m) => [m.subject, m.from, m.fromName, m.to].some((s) => String(s).toLowerCase().includes(q))).slice(0, Math.min(Number(limit) || 20, 50));
    }
    async function readMail(options = {}) {
      const { folder = "INBOX", uid } = options;
      if (!uid) throw new Error("missing uid");
      return withMailbox(folder, async (client) => {
        const msg = await client.fetchOne(String(uid), { envelope: true, flags: true, source: true }, { uid: true });
        if (!msg || !msg.source) throw new Error(`no message found for uid=${uid}`);
        const meta = summarize(msg);
        const raw = msg.source;
        const { simpleParser } = st.deps.mailparser;
        const parsed = await simpleParser(raw);
        const text = parsed.text || String(parsed.html ?? "").replace(/<style[\s\S]*?<\/style>/gi, "").replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
        return {
          ...meta,
          text: text.slice(0, BODY_LIMIT),
          truncated: text.length > BODY_LIMIT,
          hasAttachments: (parsed.attachments ?? []).length > 0
        };
      });
    }
    async function markMails(options = {}) {
      const { folder = "INBOX", uids, seen = true } = options;
      const list = (Array.isArray(uids) ? uids : [uids]).map(String);
      if (list.length === 0) return { changed: 0 };
      return withMailbox(folder, async (client) => {
        let changed = 0;
        const flag = "\\Seen";
        for (const uid of list) {
          const ok = seen ? await client.messageFlagsAdd(uid, [flag], { uid: true }) : await client.messageFlagsRemove(uid, [flag], { uid: true });
          if (ok) changed++;
        }
        return { changed };
      });
    }
    async function deleteMails(options = {}) {
      const { folder = "INBOX", uids } = options;
      const list = (Array.isArray(uids) ? uids : [uids]).map(String);
      if (list.length === 0) return { deleted: 0, trash: null };
      return withMailbox(folder, async (client) => {
        let trash = null;
        for await (const f of client.list()) {
          if (f.specialUse === "\\Trash" || /^(trash|deleted|deleted messages|\u5df2\u5220\u9664)/i.test(f.path)) {
            trash = f.path;
            break;
          }
        }
        let moved = 0;
        for (const uid of list) {
          const ok = trash ? await client.messageMove(uid, trash, { uid: true }) : await client.messageDelete(uid, { uid: true });
          if (ok) moved++;
        }
        return { deleted: moved, trash };
      });
    }
    async function sendMail(options = {}) {
      const { to, cc, subject, body } = options;
      const nd = st.deps.nodemailer;
      if (!nd) throw new Error('Dependencies are not installed: click "Install dependencies" in the settings panel');
      const c = st.config?.smtp;
      if (!c?.host || !c?.user) throw new Error("No SMTP account configured yet");
      const transport = nd.createTransport({
        host: c.host,
        port: Number(c.port) || 465,
        secure: c.tls !== false,
        auth: { user: c.user, pass: c.pass ?? "" }
      });
      const info = await transport.sendMail({
        from: c.from || c.user,
        to: String(to ?? ""),
        cc: cc ? String(cc) : void 0,
        subject: String(subject ?? "(no subject)"),
        text: String(body ?? "")
      });
      return { messageId: info.messageId, accepted: info.accepted };
    }
    async function countUnseen() {
      return withMailbox("INBOX", async (client) => ({
        uids: await client.search({ seen: false }, { uid: true }) ?? []
      }));
    }
    async function pollOnce() {
      if (!st.config?.imap?.host || !st.depsOk || st.pollBusy) return;
      st.pollBusy = true;
      try {
        const { uids } = await countUnseen();
        st.lastCheckAt = Date.now();
        const fresh = uids.filter((u) => !st.lastUnseenUids.has(u));
        st.unseenTotal = uids.length;
        if (st.firstPollDone && fresh.length > 0) {
          let subjects = [];
          try {
            const summaries = await listMails({ folder: "INBOX", limit: 10 });
            subjects = summaries.filter((m) => fresh.includes(m.uid)).slice(0, 3).map((m) => `${m.fromName || m.from}: ${m.subject}`);
          } catch {
          }
          if (st.config.notifyEnabled !== false) {
            host.notify(
              "info",
              `📬 ${fresh.length} new message${fresh.length === 1 ? "" : "s"}${subjects.length ? ` — ${subjects.join(" · ")}` : ""}`
            );
          }
          host.broadcast({
            kind: "new-mail",
            count: fresh.length,
            unseen: uids.length,
            subjects
          });
        }
        st.firstPollDone = true;
        st.lastUnseenUids = new Set(uids);
        st.status = STATUS_CONNECTED;
      } catch (err) {
        st.status = failedStatus(reasonText(err));
        dropClient();
      } finally {
        st.pollBusy = false;
        broadcastState();
      }
    }
    function restartPoller() {
      if (st.pollTimer) clearInterval(st.pollTimer);
      st.pollTimer = null;
      st.lastUnseenUids.clear();
      st.firstPollDone = false;
      const secs = Math.max(15, Math.floor(Number(st.config?.pollSec) || 60));
      if (st.config?.imap?.host && st.depsOk) {
        st.pollTimer = setInterval(() => void serialized(pollOnce), secs * 1e3);
        void serialized(pollOnce);
        if (st.bgTask) st.bgTask.update({ label: "📬 Mail polling", status: `every ${secs}s` });
        else {
          st.bgTask = host.registerBackgroundTask?.({
            id: "mail-poll",
            label: "📬 Mail polling",
            status: `every ${secs}s`,
            stop: () => {
              if (st.pollTimer) clearInterval(st.pollTimer);
              st.pollTimer = null;
              host.log("polling stopped from background panel");
            }
          }) ?? null;
        }
      } else {
        st.bgTask?.unregister();
        st.bgTask = null;
        broadcastState();
      }
    }
    const FOLDER_PARAM = {
      type: "string",
      description: "Mailbox folder path, defaults to INBOX"
    };
    function mailLines(mails) {
      return mails.map(
        (m) => `#${m.uid}${m.seen ? "" : " [unread]"} ${m.date.slice(0, 16).replace("T", " ")} ${m.fromName || m.from} — ${m.subject}`
      ).join("\n");
    }
    function aiTools() {
      return [
        {
          name: "mail_list",
          label: "List new mail",
          description: "List summaries of the recent messages in a mailbox (sender, subject, date, read state). Use it when the user asks you to check their mail or look at the inbox.",
          parameters: {
            type: "object",
            properties: {
              folder: FOLDER_PARAM,
              limit: { type: "number", description: "How many entries to return, default 30, maximum 200" },
              unseen_only: { type: "boolean", description: "Unread messages only, default false" }
            }
          },
          execute: async (_id, args) => {
            const mails = await listMails(args);
            if (mails.length === 0) return "The mailbox is empty (or has nothing unread).";
            return mailLines(mails);
          }
        },
        {
          name: "mail_read",
          label: "Read one message",
          description: "Read the full body of one message by uid (plain text, truncated when too long).",
          parameters: {
            type: "object",
            properties: {
              uid: { type: "number", description: "the #number returned by mail_list" },
              folder: FOLDER_PARAM
            },
            required: ["uid"]
          },
          execute: async (_id, args) => {
            const m = await readMail(args);
            return [
              `Subject: ${m.subject}`,
              `From: ${m.fromName ? `${m.fromName} <${m.from}>` : m.from}`,
              `Date: ${m.date}`,
              m.hasAttachments ? "(has attachments)" : "",
              "",
              m.text + (m.truncated ? "\n…(truncated)" : "")
            ].filter(Boolean).join("\n");
          }
        },
        {
          name: "mail_search",
          label: "Search mail",
          description: "Search the recent messages by keyword (matches the subject, the sender and the recipient).",
          parameters: {
            type: "object",
            properties: {
              query: { type: "string", description: "Keyword" },
              folder: FOLDER_PARAM,
              limit: { type: "number", description: "How many entries to return, default 20" }
            },
            required: ["query"]
          },
          execute: async (_id, args) => {
            const opts = args;
            const mails = await searchMails(opts);
            if (mails.length === 0) return `No messages match “${String(opts.query ?? "")}”.`;
            return mailLines(mails);
          }
        },
        {
          name: "mail_send",
          label: "Send mail",
          description: "Send one plain-text message through the configured SMTP account.",
          promptGuidelines: [
            "Confirm the recipient, the subject and the body with the user once before calling this tool."
          ],
          parameters: {
            type: "object",
            properties: {
              to: { type: "string", description: "Recipient email address" },
              cc: { type: "string", description: "Carbon copy (optional)" },
              subject: { type: "string", description: "Subject" },
              body: { type: "string", description: "Body (plain text)" }
            },
            required: ["to", "body"]
          },
          execute: async (_id, args) => {
            const r = await sendMail(args);
            return `Sent to ${(r.accepted ?? []).join(", ")}`;
          }
        },
        {
          name: "mail_manage",
          label: "Manage message state",
          description: 'Mark messages as read or unread in bulk, or delete them. action is "seen" | "unseen" | "delete".',
          parameters: {
            type: "object",
            properties: {
              action: {
                type: "string",
                enum: ["seen", "unseen", "delete"],
                description: "Operation to perform"
              },
              uids: { type: "array", items: { type: "number" }, description: "List of message uids" },
              folder: FOLDER_PARAM
            },
            required: ["action", "uids"]
          },
          execute: async (_id, args) => {
            const opts = args;
            if (opts.action === "delete") {
              const r2 = await deleteMails({ folder: opts.folder, uids: opts.uids });
              return `Deleted ${r2.deleted} message(s)${r2.trash ? ` (moved to ${r2.trash})` : ""}`;
            }
            const r = await markMails({
              folder: opts.folder,
              uids: opts.uids,
              seen: opts.action === "seen"
            });
            return `Updated the state of ${r.changed} message(s)`;
          }
        },
        {
          name: "mail_folders",
          label: "List folders",
          description: "List every folder path in the mailbox (inbox, archive, trash and so on).",
          parameters: { type: "object", properties: {} },
          execute: async () => {
            return withMailbox("INBOX", async (client) => {
              const out = [];
              for await (const f of client.list()) {
                out.push(`${f.path}${f.specialUse ? ` (${f.specialUse})` : ""}`);
              }
              return out.join("\n");
            });
          }
        }
      ];
    }
    async function refreshAiTools() {
      st.toolUnregister?.();
      st.toolUnregister = null;
      if (st.config?.aiEnabled && st.depsOk) {
        const offs = aiTools().map((t) => host.registerAgentTool(t));
        st.toolUnregister = () => offs.forEach((off) => off());
        host.log("AI mail tools enabled");
      }
    }
    const offMsg = host.onMessage((payload, from) => {
      const msg = payload ?? {};
      switch (msg.action) {
        case "get_state":
          if (from) host.sendTo(from, { kind: "state", state: publicState() });
          else broadcastState();
          break;
        case "save_config":
          void (async () => {
            try {
              await applyConfig({
                ...structuredClone(DEFAULT_CONFIG),
                ...msg.config,
                imap: { ...DEFAULT_CONFIG.imap, ...msg.config?.imap },
                smtp: { ...DEFAULT_CONFIG.smtp, ...msg.config?.smtp }
              });
              host.sendTo(from, { kind: "result", ok: true, action: "save_config" });
              host.notify("info", "📬 Mail settings saved and applied");
            } catch (err) {
              host.sendTo(from, {
                kind: "result",
                ok: false,
                action: "save_config",
                error: reasonText(err)
              });
            }
          })();
          break;
        case "install_deps":
          installDeps();
          break;
        case "list":
          void serialized(() => listMails({ folder: msg.folder, limit: msg.limit, unseen_only: msg.unseenOnly })).then((mails) => host.broadcast({ kind: "mails", mails })).catch((err) => {
            st.status = reasonText(err);
            broadcastState();
          });
          break;
        case "read":
          void serialized(() => readMail(msg)).then((mail) => host.broadcast({ kind: "mail", mail })).catch((err) => host.notify("error", `📬 Read failed: ${reasonText(err)}`));
          break;
        case "search":
          void serialized(() => searchMails(msg)).then((mails) => host.broadcast({ kind: "mails", mails })).catch((err) => host.notify("error", `📬 Search failed: ${reasonText(err)}`));
          break;
        case "mark":
          void serialized(() => markMails(msg)).then((r) => host.broadcast({ kind: "result", ok: true, action: "mark", ...r })).catch((err) => host.notify("error", `📬 Mark failed: ${reasonText(err)}`));
          break;
        case "delete":
          void serialized(() => deleteMails(msg)).then((r) => host.broadcast({ kind: "result", ok: true, action: "delete", ...r })).catch((err) => host.notify("error", `📬 Delete failed: ${reasonText(err)}`));
          break;
        case "send":
          void sendMail(msg).then(() => {
            host.notify("info", `📬 Sent to ${String(msg.to ?? "")}`);
            host.broadcast({ kind: "result", ok: true, action: "send" });
          }).catch((err) => host.notify("error", `📬 Send failed: ${reasonText(err)}`));
          break;
        default:
          host.log("unknown action", msg.action);
      }
    });
    void (async () => {
      try {
        st.config = await loadConfigSecure();
        await loadDeps();
        if (!st.depsOk) installDeps(true);
        await refreshAiTools();
        restartPoller();
        broadcastState();
        host.log("activated", st.depsOk ? "(dependencies ready)" : "(installing dependencies)");
      } catch (err) {
        host.log("activation failed:", err);
      }
    })();
    const offAttach = host.onAttach?.((clientId) => {
      host.sendTo(clientId, { kind: "state", state: publicState() });
    });
    return () => {
      offMsg();
      try {
        offAttach?.();
      } catch {
      }
      st.toolUnregister?.();
      try {
        st.bgTask?.unregister();
      } catch {
      }
      if (st.pollTimer) clearInterval(st.pollTimer);
      try {
        st.installChild?.kill();
      } catch {
      }
      dropClient();
      host.log("deactivated");
    };
  }
};
export {
  BODY_LIMIT,
  DEFAULT_CONFIG,
  index_default as default,
  loadConfig,
  summarize
};
