/* Generated by scripts/build-plugins.mjs from plugins/run-trace/src/index.ts - do not edit. */

// plugins/run-trace/src/trace.ts
var SUMMARY_CAP = 300;
var DETAIL_CAP = 8e3;
var PREVIEW_CAP = 4e3;
var MAX_CONVS = 10;
var REFRESH_DEBOUNCE_MS = 300;
var POLL_STREAMING_MS = 5e3;
var POLL_IDLE_MS = 3e4;
var WRITE_TOOL_RE = /edit|write|patch|apply|create|save|move|rename|delete|remove|mkdir/i;
var READONLY_TOOL_RE = /^(read|get|list|glob|grep|search|show|cat|fetch|query)/i;
var PATH_KEYS = /* @__PURE__ */ new Set([
  "path",
  "file",
  "filepath",
  "filePath",
  "filename",
  "fileName",
  "paths",
  "files",
  "dir",
  "cwd"
]);
function cut(value, cap) {
  const text = String(value ?? "");
  return text.length <= cap ? text : `${text.slice(0, cap)}
… [truncated]`;
}
function firstLine(value, cap = 100) {
  const line = String(value ?? "").split("\n")[0] ?? "";
  const trimmed = line.trim();
  return trimmed.length <= cap ? trimmed : `${trimmed.slice(0, cap)}…`;
}
function estTextMs(chars) {
  const n = Math.max(0, Number(chars) || 0);
  return Math.min(12e4, Math.max(800, Math.round(n * 20)));
}
function extractPaths(argsText) {
  const out = [];
  try {
    const args = JSON.parse(String(argsText ?? "null"));
    if (!args || typeof args !== "object") return out;
    const push = (value) => {
      if (typeof value !== "string") return;
      const trimmed = value.trim();
      if (trimmed.length < 1 || trimmed.length > 300) return;
      if (!/[/\\.]/.test(trimmed)) return;
      if (out.length < 10 && !out.includes(trimmed)) out.push(trimmed);
    };
    for (const [key, value] of Object.entries(args)) {
      if (!PATH_KEYS.has(key)) continue;
      if (typeof value === "string") push(value);
      else if (Array.isArray(value)) for (const item of value) push(item);
    }
  } catch {
  }
  return out;
}
function toolHeadline(toolName, argsText) {
  const name = String(toolName ?? "tool");
  if (name === "bash") {
    try {
      const command = JSON.parse(String(argsText ?? "{}"))?.command;
      if (command) return `bash · ${firstLine(command)}`;
    } catch {
    }
    return "bash";
  }
  const paths = extractPaths(argsText);
  if (paths.length) return `${name} · ${paths[0]}${paths.length > 1 ? ` (+${paths.length - 1})` : ""}`;
  const flat = firstLine(String(argsText ?? "").replace(/^\{|\}$/g, ""), 80);
  return flat ? `${name} · ${flat}` : name;
}
function blockText(blocks, type, field) {
  const parts = [];
  for (const block of blocks ?? []) {
    if (block?.type !== type) continue;
    const value = block[field];
    if (typeof value === "string" && value.trim()) parts.push(value);
  }
  return parts.join("\n");
}

// plugins/run-trace/src/index.ts
function str(value) {
  return typeof value === "string" ? value : void 0;
}
var index_default = {
  activate(host) {
    const convs = /* @__PURE__ */ new Map();
    let activeId = null;
    let refreshTimer = null;
    let pollTimer = null;
    let disposed = false;
    const getConv = (id, title) => {
      let c = convs.get(id);
      if (!c) {
        c = {
          id,
          title,
          active: false,
          isStreaming: false,
          segs: [],
          full: /* @__PURE__ */ new Map(),
          analysis: null,
          liveTools: /* @__PURE__ */ new Map(),
          updatedAt: 0
        };
        convs.set(id, c);
        while (convs.size > MAX_CONVS) {
          const oldest = [...convs.values()].filter((x) => x.id !== activeId).sort((a, b) => a.updatedAt - b.updatedAt)[0];
          if (!oldest) break;
          convs.delete(oldest.id);
        }
      }
      if (title) c.title = title;
      return c;
    };
    const summaryOf = (c) => ({
      id: c.id,
      title: c.title,
      active: c.id === activeId,
      isStreaming: c.isStreaming,
      segCount: c.segs.length,
      updatedAt: c.updatedAt,
      analysis: c.analysis
    });
    const pushState = (to) => {
      const payload = { kind: "state", conversations: [...convs.values()].map(summaryOf), activeId };
      if (to) host.sendTo(to, payload);
      else host.broadcast(payload);
    };
    function buildHistory(messages, streamingMessage) {
      const segs = [];
      const full = /* @__PURE__ */ new Map();
      const toolKeys = /* @__PURE__ */ new Set();
      let turn = 0;
      const pending = /* @__PURE__ */ new Map();
      const callInfo = /* @__PURE__ */ new Map();
      let prevEnd = 0;
      const addSeg = (seg, detail) => {
        segs.push(seg);
        if (detail !== void 0) full.set(seg.key, detail);
        const e = seg.end ?? seg.t;
        if (e > prevEnd) prevEnd = e;
        return seg;
      };
      const all = streamingMessage ? [...messages ?? [], { ...streamingMessage, _live: true }] : messages ?? [];
      const nextTByMsg = /* @__PURE__ */ new Map();
      {
        let nxt;
        for (let i = all.length - 1; i >= 0; i--) {
          const message = all[i];
          if (!message) continue;
          nextTByMsg.set(message, nxt);
          const ts = message.timestamp;
          if (typeof ts === "number") nxt = ts;
        }
      }
      for (const m of all) {
        const live = !!m._live;
        const t = m.timestamp ?? Date.now();
        if (m.role === "user") {
          turn += 1;
          const text = blockText(m.content, "text", "text").trim() || "(attachment or empty message)";
          addSeg(
            {
              key: `h-${m.id}`,
              kind: "user",
              lane: "input",
              t,
              end: t,
              title: `User · turn ${turn}`,
              summary: cut(text, SUMMARY_CAP),
              source: "User",
              status: "done",
              turn,
              meta: { chars: text.length }
            },
            cut(text, DETAIL_CAP)
          );
        } else if (m.role === "assistant") {
          const blocks = m.content ?? [];
          const ests = [];
          let totalEst = 0;
          for (const b of blocks) {
            const thinking = str(b?.thinking);
            const text = str(b?.text);
            if (b?.type === "thinking" && thinking?.trim()) {
              const e = live ? 0 : estTextMs(thinking.length);
              ests.push(e);
              totalEst += e;
            } else if (b?.type === "text" && text?.trim()) {
              const e = live ? 0 : estTextMs(text.length);
              ests.push(e);
              totalEst += e;
            }
          }
          let cursor = Math.max(t, prevEnd);
          if (!live && totalEst > 0) {
            const nextT = nextTByMsg.get(m);
            const budget = nextT !== void 0 ? Math.max(0, nextT - t) : Infinity;
            if (totalEst > budget) {
              const s = budget > 0 ? budget / totalEst : 0;
              for (let i = 0; i < ests.length; i++) ests[i] = Math.max(1, Math.floor((ests[i] ?? 0) * s));
            }
          }
          let ei = 0;
          let bi = 0;
          for (const b of blocks) {
            const thinking = str(b?.thinking);
            const text = str(b?.text);
            if (b?.type === "thinking" && thinking?.trim()) {
              const est = ests[ei++] ?? 0;
              const start = cursor;
              const end = live ? t : start + Math.max(1, est);
              cursor = end;
              addSeg(
                {
                  key: `h-${m.id}-${bi++}`,
                  kind: "thinking",
                  lane: "model",
                  t: start,
                  end,
                  ...live ? {} : { dur: Math.max(0, end - start) },
                  title: "Thinking",
                  summary: cut(thinking.trim(), SUMMARY_CAP),
                  source: "Model · thinking",
                  status: live ? "running" : "done",
                  turn,
                  meta: { chars: thinking.length }
                },
                cut(thinking, DETAIL_CAP)
              );
            } else if (b?.type === "text" && text?.trim()) {
              const est = ests[ei++] ?? 0;
              const start = cursor;
              const end = live ? t : start + Math.max(1, est);
              cursor = end;
              addSeg(
                {
                  key: `h-${m.id}-${bi++}`,
                  kind: "text",
                  lane: "model",
                  t: start,
                  end,
                  ...live ? {} : { dur: Math.max(0, end - start) },
                  title: "Answer",
                  summary: cut(text.trim(), SUMMARY_CAP),
                  source: "Model · answer",
                  status: live ? "running" : "done",
                  turn,
                  meta: { chars: text.length }
                },
                cut(text, DETAIL_CAP)
              );
            } else if (b?.type === "toolCall" && b.id) {
              const callId = String(b.id);
              if (liveTools(currentConvId, callId)) {
                callInfo.set(callId, { argsText: str(b.argumentsText) ?? "null", ts: Math.max(t, cursor) });
                continue;
              }
              const argsText = str(b.argumentsText) ?? "null";
              const toolName = str(b.name);
              const toolT = Math.max(t, cursor);
              callInfo.set(callId, { argsText, ts: toolT });
              const readonly = READONLY_TOOL_RE.test(toolName ?? "");
              const seg = {
                key: `h-${callId}`,
                kind: "tool",
                lane: "tools",
                t: toolT,
                end: toolT,
                title: `${readonly ? "📖" : "🔧"} ${toolHeadline(toolName, argsText)}`,
                summary: live ? "Running…" : "(waiting for result)",
                source: `Tool · ${toolName}`,
                status: "running",
                turn,
                meta: {
                  tool: toolName,
                  toolCallId: callId,
                  args: cut(argsText, PREVIEW_CAP),
                  files: extractPaths(argsText)
                }
              };
              toolKeys.add(callId);
              pending.set(callId, seg);
              addSeg(seg, cut(argsText, DETAIL_CAP));
            }
          }
        } else if (m.role === "toolResult" && m.toolCallId) {
          const toolCallId = m.toolCallId;
          const text = blockText(m.content, "text", "text");
          const info = callInfo.get(toolCallId);
          const dur = info && m.timestamp && info.ts ? Math.max(0, m.timestamp - info.ts) : void 0;
          toolKeys.add(toolCallId);
          const seg = pending.get(toolCallId);
          const toolName = m.toolName ?? seg?.meta?.tool ?? "tool";
          if (seg) {
            pending.delete(toolCallId);
            seg.status = m.isError ? "error" : "done";
            seg.end = Math.max(m.timestamp ?? seg.t, seg.t);
            const realDur = info && seg.end !== void 0 && info.ts !== void 0 ? Math.max(0, seg.end - info.ts) : void 0;
            if (realDur !== void 0) seg.dur = realDur;
            seg.title = `${m.isError ? "❌" : "✅"} ${toolHeadline(toolName, info?.argsText)}`;
            seg.summary = cut(
              m.isError ? `Failed${realDur !== void 0 ? ` · ${(realDur / 1e3).toFixed(1)}s` : ""}` : text.trim().slice(0, 200) || "Done",
              SUMMARY_CAP
            );
            seg.meta = { ...seg.meta, result: cut(text, PREVIEW_CAP), dur: realDur };
            full.set(seg.key, cut(text || "(no output)", DETAIL_CAP));
            if (seg.end > prevEnd) prevEnd = seg.end;
          } else {
            addSeg(
              {
                key: `h-${toolCallId}`,
                kind: "tool",
                lane: "tools",
                t,
                end: m.timestamp ?? t,
                ...dur !== void 0 ? { dur } : {},
                title: `${m.isError ? "❌" : "✅"} ${toolName}`,
                summary: cut(text.trim().slice(0, 200) || (m.isError ? "Failed" : "Done"), SUMMARY_CAP),
                source: `Tool · ${toolName}`,
                status: m.isError ? "error" : "done",
                turn,
                meta: { tool: toolName, toolCallId, result: cut(text, PREVIEW_CAP), dur }
              },
              cut(text || "(no output)", DETAIL_CAP)
            );
          }
          if (!m.isError && WRITE_TOOL_RE.test(String(toolName)) && !READONLY_TOOL_RE.test(String(toolName))) {
            const files = extractPaths(info?.argsText);
            if (files.length) {
              addSeg(
                {
                  key: `h-${toolCallId}-files`,
                  kind: "file",
                  lane: "tools",
                  t,
                  end: m.timestamp ?? t,
                  title: `📝 ${files.length} file(s) changed`,
                  summary: files.slice(0, 3).join(", ") + (files.length > 3 ? ` (of ${files.length} total)` : ""),
                  source: `Tool · ${toolName}`,
                  status: "done",
                  turn,
                  meta: { tool: toolName, files }
                },
                files.join("\n")
              );
            }
          }
        } else if (m.role === "bashExecution") {
          const b = (m.content ?? []).find((x) => x?.type === "bash") ?? {};
          const command = str(b.command) ?? "";
          const output = String(b.output ?? "").trim().slice(0, 200) || "Done";
          const failed = !!b.cancelled || !!b.exitCode && b.exitCode !== 0;
          addSeg(
            {
              key: `h-${m.id}`,
              kind: "tool",
              lane: "tools",
              t,
              end: t,
              title: `${failed ? "❌" : "✅"} bash · ${firstLine(b.command)}`,
              summary: cut(output, SUMMARY_CAP),
              source: "Tool · bash",
              status: failed ? "error" : "done",
              turn,
              meta: { tool: "bash", command: cut(command, PREVIEW_CAP), exitCode: b.exitCode }
            },
            `$ ${command}
${cut(String(b.output ?? ""), DETAIL_CAP)}`
          );
        } else if (m.role === "compactionSummary" || m.role === "branchSummary") {
          const text = blockText(m.content, "text", "text").trim();
          if (text) {
            addSeg(
              {
                key: `h-${m.id}`,
                kind: "system",
                lane: "model",
                t,
                end: t,
                title: m.role === "compactionSummary" ? "🗜️ context compacted" : "🌿 branch summary",
                summary: cut(text, SUMMARY_CAP),
                source: "System",
                status: "done",
                turn,
                meta: { chars: text.length }
              },
              cut(text, DETAIL_CAP)
            );
          }
        }
      }
      return { segs, full, toolKeys };
    }
    let currentConvId = null;
    const liveTools = (convId, toolCallId) => {
      const c = convs.get(convId ?? "");
      return c ? c.liveTools.has(toolCallId) : false;
    };
    function computeAnalysis(c) {
      const tools = /* @__PURE__ */ new Map();
      let turns = 0;
      const filesChanged = [];
      let chars = 0;
      let toolErrs = 0;
      let toolMs = 0;
      const counts = { user: 0, thinking: 0, text: 0, tool: 0, file: 0, system: 0 };
      for (const s of c.segs) {
        if (s.kind in counts) counts[s.kind] += 1;
        if (s.kind === "user") turns = Math.max(turns, s.turn);
        if (s.meta?.chars) chars += s.meta.chars;
        const tool = s.meta?.tool;
        if (s.kind === "tool" && tool) {
          const stat = tools.get(tool) ?? { name: tool, calls: 0, ms: 0, errs: 0 };
          stat.calls += 1;
          if (s.dur !== void 0) {
            stat.ms += s.dur;
            toolMs += s.dur;
          }
          if (s.status === "error") {
            stat.errs += 1;
            toolErrs += 1;
          }
          tools.set(tool, stat);
        }
        const files = s.meta?.files;
        if (s.kind === "file" && Array.isArray(files)) {
          for (const file of files) if (!filesChanged.includes(file)) filesChanged.push(file);
        }
      }
      const startedAt = c.segs.length ? c.segs[0]?.t ?? c.updatedAt : c.updatedAt;
      const lastEnd = c.segs.reduce((max, s) => Math.max(max, s.end ?? s.t), startedAt);
      return {
        startedAt,
        totalMs: Math.max(0, lastEnd - startedAt),
        turns,
        counts,
        toolCalls: [...tools.values()].reduce((n, x) => n + x.calls, 0),
        toolErrs,
        toolMs,
        chars,
        filesChanged: filesChanged.slice(0, 50),
        tools: [...tools.values()].sort((a, b) => b.ms - a.ms).slice(0, 12)
      };
    }
    function refresh() {
      if (disposed) return;
      let snap;
      try {
        snap = host.getActiveConversation?.();
      } catch (err) {
        host.log("getActiveConversation failed:", err instanceof Error ? err.message : err);
        return;
      }
      if (!snap) return;
      const c = getConv(snap.conversationId, snap.title);
      const firstSeen = c.updatedAt === 0;
      const becameActive = activeId !== c.id;
      currentConvId = c.id;
      c.isStreaming = !!snap.isStreaming;
      c.title = snap.title || c.title;
      const { segs, full, toolKeys } = buildHistory(snap.messages, snap.streamingMessage);
      for (const [id] of c.liveTools) {
        if (toolKeys.has(id)) c.liveTools.delete(id);
      }
      const live = [...c.liveTools.values()];
      c.segs = [...segs, ...live];
      c.full = full;
      for (const s of live) if (s.detail !== void 0) c.full.set(s.key, s.detail);
      c.analysis = computeAnalysis(c);
      c.updatedAt = Date.now();
      if (becameActive) {
        activeId = c.id;
        for (const x of convs.values()) x.active = x.id === activeId;
      }
      if (becameActive || firstSeen) pushState();
      host.broadcast({ kind: "segs", convId: c.id, reset: true, segs: c.segs });
      host.broadcast({ kind: "conv_update", conv: summaryOf(c) });
      if (firstSeen) host.broadcast({ kind: "conv_new", conv: summaryOf(c) });
    }
    const scheduleRefresh = () => {
      if (refreshTimer) return;
      refreshTimer = setTimeout(() => {
        refreshTimer = null;
        refresh();
      }, REFRESH_DEBOUNCE_MS);
    };
    const offRun = host.onRunEvent((ev) => {
      try {
        if (ev.type === "tool_start") {
          const c = getConv(ev.conversationId ?? currentConvId ?? "unknown", void 0);
          const readonly = READONLY_TOOL_RE.test(String(ev.toolName ?? ""));
          const headline = toolHeadline(ev.toolName, ev.argsText);
          const argsText = String(ev.argsText ?? "null");
          const detail = cut(argsText, DETAIL_CAP);
          const seg = {
            key: `L-${ev.toolCallId ?? `${Date.now()}`}`,
            kind: "tool",
            lane: "tools",
            t: ev.at,
            end: ev.at,
            title: `${readonly ? "📖" : "🔧"} ${headline}`,
            headline,
            summary: "Running…",
            source: `Tool · ${ev.toolName}`,
            status: "running",
            turn: 0,
            meta: {
              tool: ev.toolName,
              toolCallId: ev.toolCallId,
              args: cut(argsText, PREVIEW_CAP),
              files: extractPaths(ev.argsText)
            },
            detail
          };
          if (ev.toolCallId) c.liveTools.set(ev.toolCallId, seg);
          c.segs = [...c.segs, seg];
          c.full.set(seg.key, detail);
          host.broadcast({ kind: "segs", convId: c.id, reset: false, segs: [seg] });
          return;
        }
        if (ev.type === "tool_end") {
          const c = convs.get(ev.conversationId ?? "");
          const seg = ev.toolCallId ? c?.liveTools.get(ev.toolCallId) : void 0;
          if (seg && c) {
            const secs = ev.durationMs !== void 0 ? ` · ${(ev.durationMs / 1e3).toFixed(1)}s` : "";
            const preview = cut(String(ev.resultText ?? ""), DETAIL_CAP).trim();
            const patch = {
              status: ev.isError ? "error" : "done",
              end: ev.at,
              ...ev.durationMs !== void 0 ? { dur: ev.durationMs } : {},
              title: `${ev.isError ? "❌" : "✅"} ${seg.headline ?? ev.toolName}`,
              summary: cut(
                ev.isError ? `Failed${secs}` : preview ? `${preview.slice(0, 200)}${secs}` : `Done${secs}`,
                SUMMARY_CAP
              ),
              source: seg.source,
              turn: seg.turn,
              meta: { ...seg.meta, result: cut(String(ev.resultText ?? ""), PREVIEW_CAP), dur: ev.durationMs }
            };
            Object.assign(seg, patch);
            const detail = preview || "(no output)";
            seg.detail = detail;
            c.full.set(seg.key, detail);
            host.broadcast({ kind: "seg_update", convId: c.id, key: seg.key, patch });
          }
          scheduleRefresh();
          return;
        }
        scheduleRefresh();
      } catch (err) {
        host.log("run event failed:", err instanceof Error ? err.message : err);
      }
    });
    const offMsg = host.onMessage((payload, from) => {
      const msg = payload ?? {};
      try {
        switch (msg.action) {
          case "state":
            pushState(from);
            scheduleRefresh();
            break;
          case "get_conv": {
            const c = convs.get(String(msg.convId ?? ""));
            if (c && from) {
              host.sendTo(from, { kind: "segs", convId: c.id, reset: true, segs: c.segs });
              host.sendTo(from, { kind: "conv_update", conv: summaryOf(c) });
            } else if (from) {
              scheduleRefresh();
              host.sendTo(from, { kind: "segs", convId: String(msg.convId ?? ""), reset: true, segs: [] });
            }
            break;
          }
          case "get_seg": {
            const c = convs.get(String(msg.convId ?? ""));
            const seg = c?.segs.find((s) => s.key === String(msg.key ?? ""));
            if (c && seg && from) {
              host.sendTo(from, {
                kind: "seg_detail",
                convId: c.id,
                key: seg.key,
                detail: c.full.get(seg.key) ?? seg.summary ?? "",
                seg,
                analysis: segAnalysis(c, seg)
              });
            }
            break;
          }
          case "clear":
            convs.clear();
            activeId = null;
            currentConvId = null;
            host.broadcast({ kind: "cleared" });
            pushState();
            scheduleRefresh();
            break;
          default:
            break;
        }
      } catch (err) {
        host.log("message failed:", err instanceof Error ? err.message : err);
      }
    });
    function segAnalysis(c, seg) {
      const a = c.analysis;
      const total = c.segs.length || 1;
      const idx = c.segs.findIndex((s) => s.key === seg.key);
      const base = {
        position: idx >= 0 ? `#${idx + 1}/${total}` : "—",
        turnText: seg.turn ? `Turn ${seg.turn}` : "—",
        convTurns: a?.turns ?? 0
      };
      const tool = seg.meta?.tool;
      if (seg.kind === "tool" && tool && a) {
        const stat = a.tools.find((x) => x.name === tool);
        return {
          ...base,
          tool: stat ?? { name: tool, calls: 1, ms: seg.dur ?? 0, errs: seg.status === "error" ? 1 : 0 },
          convToolCalls: a.toolCalls,
          convToolMs: a.toolMs
        };
      }
      return base;
    }
    const offConvChanged = host.onConversationChanged ? host.onConversationChanged(() => scheduleRefresh()) : () => {
    };
    const offAttach = host.onAttach((clientId) => {
      try {
        pushState(clientId);
        scheduleRefresh();
      } catch (err) {
        host.log("attach push failed:", err instanceof Error ? err.message : err);
      }
    });
    const poll = () => {
      if (disposed) return;
      try {
        const streaming = [...convs.values()].some((c) => c.isStreaming);
        refresh();
        pollTimer = setTimeout(poll, streaming ? POLL_STREAMING_MS : POLL_IDLE_MS);
      } catch {
        pollTimer = setTimeout(poll, POLL_IDLE_MS);
      }
    };
    refresh();
    pollTimer = setTimeout(poll, POLL_STREAMING_MS);
    host.log("activated (v2: open-conversation timeline + analysis)");
    return () => {
      disposed = true;
      offRun();
      offMsg();
      offAttach();
      offConvChanged();
      if (refreshTimer) clearTimeout(refreshTimer);
      if (pollTimer) clearTimeout(pollTimer);
    };
  }
};
export {
  index_default as default,
  estTextMs,
  extractPaths,
  toolHeadline
};
