/**
 * Build smoke test for the webmail plugin.
 *
 * The unit tests exercise plugins/webmail/src/*.ts, which cannot see a
 * misconfigured esbuild step. This file runs the real shared builder and then
 * imports what it produced, proving:
 *   - the compiled artifacts land at the two filenames pi-web-ui hardcodes;
 *   - they are valid ESM whose default export has the shape the host expects;
 *   - the client bundle is self-contained (no bare npm specifier survives, which
 *     would throw the moment a browser evaluated it);
 *   - the server bundle only imports node builtins at top level, so importing it
 *     cannot fail with MODULE_NOT_FOUND before the drivers are auto-installed;
 *   - both artifacts are English and are genuinely build output, not the stale
 *     hand-written files upstream shipped at these paths.
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { artifactRelPaths, buildPlugin } from "../helpers/plugin-build";
import {
	importClientArtifact,
	importServerArtifact,
	isClientEntry,
	isServerEntry,
	loadPlugin,
} from "../helpers/plugin-contract";
import { findCjk, formatCjkHits, repoPath } from "../helpers/repo-files";
import type { PluginClientEntry, PluginServerEntry } from "../helpers/mock-host";

const ID = "webmail";
const built = buildPlugin(ID);

/** Specifiers of every top-level `import ... from "x"` / `export ... from "x"`
 *  statement in a bundle. Multi-line import lists are not matched, which is fine:
 *  esbuild emits one statement per line for the two files this checks. */
function topLevelSpecifiers(source: string): string[] {
	const found: string[] = [];
	const pattern = /^[ \t]*(?:import|export)\b[^;\n]*?["']([^"']+)["'][ \t]*;?[ \t]*$/gm;
	for (const match of source.matchAll(pattern)) found.push(match[1]!);
	return found;
}

describe("webmail build", () => {
	it("compiles both entry points with the shared builder", () => {
		expect(built.ok, `build failed:\n${built.stderr}\n${built.stdout}`).toBe(true);
		expect(built.status).toBe(0);
		expect(built.artifacts.sort()).toEqual([artifactRelPaths(ID).client, artifactRelPaths(ID).server].sort());
		expect(built.serverEntry).toBeDefined();
		expect(built.clientEntry).toBeDefined();
	});

	it("writes generated output, not the hand-written files it replaced", () => {
		for (const artifact of [built.serverEntry, built.clientEntry]) {
			const firstLine = readFileSync(artifact!, "utf8").split("\n")[0]!;
			expect(firstLine, `${artifact} does not look like build output`).toContain(
				"Generated by scripts/build-plugins.mjs",
			);
		}
	});

	it("has no manifest id, so the host derives it from the directory name", () => {
		const plugin = loadPlugin(ID);
		expect(plugin.dirName).toBe(ID);
		expect(plugin.id).toBe(ID);
		expect(plugin.manifest.id).toBeUndefined();
		expect(plugin.hasServerSource).toBe(true);
		expect(plugin.hasClientSource).toBe(true);
	});

	it("produces a server artifact the host can activate", async () => {
		const mod = await importServerArtifact(ID);
		expect(isServerEntry(mod), "index.mjs has no default export with activate()").toBe(true);
		const entry = (mod as { default: PluginServerEntry }).default;
		expect(typeof entry.activate).toBe("function");
		expect(entry.activate.length).toBe(1);
	});

	it("produces a client artifact the frontend loader can mount", async () => {
		const mod = await importClientArtifact(ID);
		expect(isClientEntry(mod), "client/entry.mjs has no default export with mount()").toBe(true);
		const entry = (mod as { default: PluginClientEntry }).default;
		expect(typeof entry.mount).toBe("function");
		expect(entry.mount!.length).toBe(2);
		expect(entry.renderers).toBeUndefined();
	});

	it("leaves no bare npm import in the client bundle", () => {
		const source = readFileSync(built.clientEntry!, "utf8");
		const bare = topLevelSpecifiers(source).filter((spec) => !spec.startsWith(".") && !spec.startsWith("/"));
		expect(bare, `bare specifiers would throw in the browser: ${bare.join(", ")}`).toEqual([]);
		expect(source.length).toBeGreaterThan(1000);
	});

	it("imports only node builtins at the top level of the server bundle", () => {
		const source = readFileSync(built.serverEntry!, "utf8");
		const specifiers = topLevelSpecifiers(source);
		// The mail drivers are imported at runtime after auto-install, never here.
		expect(specifiers.length).toBeGreaterThan(0);
		expect(specifiers.every((spec) => spec.startsWith("node:"))).toBe(true);
		expect(source).not.toMatch(/^[ \t]*import\b[^;\n]*["']imapflow["']/m);
		expect(source).not.toMatch(/^[ \t]*import\b[^;\n]*["']nodemailer["']/m);
	});

	it("compiles to artifacts that contain no CJK character", () => {
		for (const rel of built.artifacts) {
			const hits = findCjk(repoPath(rel));
			expect(formatCjkHits(rel, hits), `${rel} still contains CJK`).toEqual([]);
		}
	});

	it("keeps the secret names and action names intact in the compiled server", () => {
		const source = readFileSync(built.serverEntry!, "utf8");
		for (const preserved of [
			"imap_pass",
			"smtp_pass",
			"config.json",
			"mail_list",
			"mail_read",
			"mail_search",
			"mail_send",
			"mail_manage",
			"mail_folders",
			"mail-poll",
			"get_state",
			"save_config",
			"install_deps",
			"unseen_only",
			"new-mail",
		]) {
			expect(source, `the compiled server lost the protocol value "${preserved}"`).toContain(preserved);
		}
	});

	it("keeps the action names the view sends intact in the compiled client", () => {
		const source = readFileSync(built.clientEntry!, "utf8");
		for (const preserved of ["get_state", "save_config", "install_deps", "new-mail", "pi-web-ui:plugin-run-command"]) {
			expect(source, `the compiled client lost the protocol value "${preserved}"`).toContain(preserved);
		}
	});
});
